/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Muhammad Waseem
 */
public class BAR_B_Q_Page extends javax.swing.JFrame {

    private int Total_Amount = 0;
    /**
     * Creates new form BAR_B_Q_Page
     */
    public BAR_B_Q_Page() {
        initComponents();
    }

    
    public void Total_BBQ(int amount)
    {
        this.Total_Amount += amount;
    }
    
    public void Import_File() {
        String Filepath = "E:\\Rice.txt";
        File file = new File(Filepath);
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Object[] lines = br.lines().toArray();

            for (int i = 0; i < lines.length; i++) {
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Table2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Export_File() {
        String Filepath = "E:\\Rice.txt";
        File file = new File(Filepath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            for (int i = 0; i < jTable1.getRowCount(); i++) {
                for (int j = 0; j < jTable1.getColumnCount(); j++) {
                    bw.write(jTable1.getValueAt(i, j).toString() + " ");
                }
                bw.newLine();
            }
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Table.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    public void BBQ(String name, int price)
    {

        int Quantity = Integer.parseInt(JOptionPane.showInputDialog(null, "Quantity"));
        if (Quantity > 0) 
        {
            int Total = price * Quantity;
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]
            {
                name,
                price,
                Quantity,
                Total

            });
            this.Total_Amount += Total;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ALL_BUTTON = new javax.swing.JButton();
        BAR_B_Q_BUTTON1 = new javax.swing.JButton();
        KARAHI_BUTTON = new javax.swing.JButton();
        RICE_BUTTON = new javax.swing.JButton();
        VEGETABLES_BUTTON = new javax.swing.JButton();
        BEANS_BUTTON = new javax.swing.JButton();
        CHINES_DISHES_BUTTON = new javax.swing.JButton();
        FAST_FOOD_BUTTON = new javax.swing.JButton();
        SWEETS_BUTTON = new javax.swing.JButton();
        COLD_DRINKS_BUTTON = new javax.swing.JButton();
        TUNDOOR_BUTTON = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Seekh_Kabab_Pannel = new javax.swing.JPanel();
        Seekh_Kabab_Label = new javax.swing.JLabel();
        Seekh_Kabab_Price = new javax.swing.JLabel();
        Behari_Kabab_Pannel = new javax.swing.JPanel();
        Behari_Kabab_Label = new javax.swing.JLabel();
        Behari_Kabab_Price = new javax.swing.JLabel();
        Malai_Boti_Pannel = new javax.swing.JPanel();
        Malai_Boti_Label = new javax.swing.JLabel();
        Malai_Boti_Price = new javax.swing.JLabel();
        Chicken_Tikka_Pannel = new javax.swing.JPanel();
        Chicken_Tikka_Label = new javax.swing.JLabel();
        Chicken_Tikka_Price = new javax.swing.JLabel();
        Chicken_Chest_Pannel = new javax.swing.JPanel();
        Chicken_Chest_Label = new javax.swing.JLabel();
        Chicken_Chest_Price = new javax.swing.JLabel();
        Chicken_Boti_Pannel = new javax.swing.JPanel();
        Chicken_Boti_Label = new javax.swing.JLabel();
        Chicken_Boti_Price = new javax.swing.JLabel();
        Gola_Kabab_Pannel = new javax.swing.JPanel();
        Gola_Kabab_Label = new javax.swing.JLabel();
        Gola_Kabab_Price = new javax.swing.JLabel();
        Reshmi_Kabab_Pannel = new javax.swing.JPanel();
        Reshmi_Kabab_Label = new javax.swing.JLabel();
        Reshmi_Kabab_Price = new javax.swing.JLabel();
        Vegetable_Kabab_Panel = new javax.swing.JPanel();
        Vegetable_Kabab_Label = new javax.swing.JLabel();
        Vegetable_Kabab_Price = new javax.swing.JLabel();
        Mutton_Boti_Pannel = new javax.swing.JPanel();
        Mutton_Boti_Label = new javax.swing.JLabel();
        Mutton_Boti_Price = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Cash_Remained = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Total_TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Cash_Recieved = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Delete_Row = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ALL_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        ALL_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ALL_BUTTON.setText("ALL PRODUCTS");
        ALL_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALL_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(ALL_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        BAR_B_Q_BUTTON1.setBackground(new java.awt.Color(51, 255, 51));
        BAR_B_Q_BUTTON1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BAR_B_Q_BUTTON1.setText("BAR-B-Q");
        BAR_B_Q_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAR_B_Q_BUTTON1ActionPerformed(evt);
            }
        });
        jPanel2.add(BAR_B_Q_BUTTON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 50));

        KARAHI_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        KARAHI_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        KARAHI_BUTTON.setText("KARAHI");
        KARAHI_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KARAHI_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(KARAHI_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 50));

        RICE_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        RICE_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RICE_BUTTON.setText("RICE");
        RICE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RICE_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(RICE_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 50));

        VEGETABLES_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        VEGETABLES_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        VEGETABLES_BUTTON.setText("VEGETABLES");
        VEGETABLES_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VEGETABLES_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(VEGETABLES_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 50));

        BEANS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        BEANS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BEANS_BUTTON.setText("BEANS");
        BEANS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEANS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(BEANS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 150, 50));

        CHINES_DISHES_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        CHINES_DISHES_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CHINES_DISHES_BUTTON.setText("CHINESE DISHES");
        CHINES_DISHES_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHINES_DISHES_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(CHINES_DISHES_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 150, 50));

        FAST_FOOD_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        FAST_FOOD_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        FAST_FOOD_BUTTON.setText("FAST FOOD");
        FAST_FOOD_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAST_FOOD_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(FAST_FOOD_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 150, 50));

        SWEETS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        SWEETS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SWEETS_BUTTON.setText("SWEETS");
        SWEETS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SWEETS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(SWEETS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 150, 50));

        COLD_DRINKS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        COLD_DRINKS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        COLD_DRINKS_BUTTON.setText("COLD DRINKS");
        COLD_DRINKS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COLD_DRINKS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(COLD_DRINKS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 150, 50));

        TUNDOOR_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        TUNDOOR_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TUNDOOR_BUTTON.setText("FROM TUNDOOR");
        TUNDOOR_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUNDOOR_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(TUNDOOR_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 150, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/BBQ/Seekh Kabab.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/BBQ/Behari Kabab.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/BBQ/Malai Boti.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/BBQ/Chicken Tikka.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/BBQ/Chicken Chest Piece.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/BBQ/Chicken Boti.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/BBQ/Gola Kabab.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/BBQ/Reshmi Kabab.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/BBQ/Vegetable Seekh Kabab.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/BBQ/Mutton Boti.png"))); // NOI18N

        Seekh_Kabab_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Seekh_Kabab_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Seekh_Kabab_PannelMouseClicked(evt);
            }
        });
        Seekh_Kabab_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Seekh_Kabab_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Seekh_Kabab_Label.setForeground(new java.awt.Color(204, 0, 0));
        Seekh_Kabab_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Seekh_Kabab_Label.setText("Seekh_Kabab");
        Seekh_Kabab_Pannel.add(Seekh_Kabab_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 75, -1));

        Seekh_Kabab_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Seekh_Kabab_Price.setForeground(new java.awt.Color(204, 0, 0));
        Seekh_Kabab_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Seekh_Kabab_Price.setText("Price = 80Rs.");
        Seekh_Kabab_Pannel.add(Seekh_Kabab_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 75, -1));

        Behari_Kabab_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Behari_Kabab_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Behari_Kabab_PannelMouseClicked(evt);
            }
        });
        Behari_Kabab_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Behari_Kabab_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Behari_Kabab_Label.setForeground(new java.awt.Color(204, 0, 0));
        Behari_Kabab_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Behari_Kabab_Label.setText("Behari_Kabab");
        Behari_Kabab_Pannel.add(Behari_Kabab_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, -1));

        Behari_Kabab_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Behari_Kabab_Price.setForeground(new java.awt.Color(204, 0, 0));
        Behari_Kabab_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Behari_Kabab_Price.setText("Price = 120Rs.");
        Behari_Kabab_Pannel.add(Behari_Kabab_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        Malai_Boti_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Malai_Boti_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Malai_Boti_PannelMouseClicked(evt);
            }
        });
        Malai_Boti_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Malai_Boti_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Malai_Boti_Label.setForeground(new java.awt.Color(204, 0, 0));
        Malai_Boti_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Malai_Boti_Label.setText("Malai_Boti");
        Malai_Boti_Pannel.add(Malai_Boti_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 65, -1));

        Malai_Boti_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Malai_Boti_Price.setForeground(new java.awt.Color(204, 0, 0));
        Malai_Boti_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Malai_Boti_Price.setText("Price = 80Rs.");
        Malai_Boti_Pannel.add(Malai_Boti_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        Chicken_Tikka_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Chicken_Tikka_Pannel.setMinimumSize(new java.awt.Dimension(124, 45));
        Chicken_Tikka_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chicken_Tikka_PannelMouseClicked(evt);
            }
        });
        Chicken_Tikka_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Chicken_Tikka_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chicken_Tikka_Label.setForeground(new java.awt.Color(204, 0, 0));
        Chicken_Tikka_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken_Tikka_Label.setText("Chicken_Tikka");
        Chicken_Tikka_Pannel.add(Chicken_Tikka_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        Chicken_Tikka_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chicken_Tikka_Price.setForeground(new java.awt.Color(204, 0, 0));
        Chicken_Tikka_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken_Tikka_Price.setText("Price = 300Rs.");
        Chicken_Tikka_Pannel.add(Chicken_Tikka_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        Chicken_Chest_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Chicken_Chest_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chicken_Chest_PannelMouseClicked(evt);
            }
        });
        Chicken_Chest_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Chicken_Chest_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chicken_Chest_Label.setForeground(new java.awt.Color(204, 0, 0));
        Chicken_Chest_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken_Chest_Label.setText("Chicken_Chest");
        Chicken_Chest_Pannel.add(Chicken_Chest_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, -1));

        Chicken_Chest_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chicken_Chest_Price.setForeground(new java.awt.Color(204, 0, 0));
        Chicken_Chest_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken_Chest_Price.setText("Price = 220Rs.");
        Chicken_Chest_Pannel.add(Chicken_Chest_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        Chicken_Boti_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Chicken_Boti_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chicken_Boti_PannelMouseClicked(evt);
            }
        });
        Chicken_Boti_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Chicken_Boti_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chicken_Boti_Label.setForeground(new java.awt.Color(204, 0, 0));
        Chicken_Boti_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken_Boti_Label.setText("Chicken_Boti");
        Chicken_Boti_Pannel.add(Chicken_Boti_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 74, -1));

        Chicken_Boti_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chicken_Boti_Price.setForeground(new java.awt.Color(204, 0, 0));
        Chicken_Boti_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken_Boti_Price.setText("Price = 150Rs.");
        Chicken_Boti_Pannel.add(Chicken_Boti_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        Gola_Kabab_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Gola_Kabab_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Gola_Kabab_PannelMouseClicked(evt);
            }
        });
        Gola_Kabab_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gola_Kabab_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Gola_Kabab_Label.setForeground(new java.awt.Color(204, 0, 0));
        Gola_Kabab_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gola_Kabab_Label.setText("Gola_Kabab");
        Gola_Kabab_Pannel.add(Gola_Kabab_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 74, -1));

        Gola_Kabab_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Gola_Kabab_Price.setForeground(new java.awt.Color(204, 0, 0));
        Gola_Kabab_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gola_Kabab_Price.setText("Price = 150Rs.");
        Gola_Kabab_Pannel.add(Gola_Kabab_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        Reshmi_Kabab_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Reshmi_Kabab_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reshmi_Kabab_PannelMouseClicked(evt);
            }
        });
        Reshmi_Kabab_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reshmi_Kabab_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Reshmi_Kabab_Label.setForeground(new java.awt.Color(204, 0, 0));
        Reshmi_Kabab_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reshmi_Kabab_Label.setText("Reshmi_Kabab");
        Reshmi_Kabab_Pannel.add(Reshmi_Kabab_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, -1));

        Reshmi_Kabab_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Reshmi_Kabab_Price.setForeground(new java.awt.Color(204, 0, 0));
        Reshmi_Kabab_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reshmi_Kabab_Price.setText("Price = 130Rs.");
        Reshmi_Kabab_Pannel.add(Reshmi_Kabab_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        Vegetable_Kabab_Panel.setBackground(new java.awt.Color(204, 204, 0));
        Vegetable_Kabab_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Vegetable_Kabab_PanelMouseClicked(evt);
            }
        });
        Vegetable_Kabab_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Vegetable_Kabab_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Vegetable_Kabab_Label.setForeground(new java.awt.Color(204, 0, 0));
        Vegetable_Kabab_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Vegetable_Kabab_Label.setText("Vegetable_Kabab");
        Vegetable_Kabab_Panel.add(Vegetable_Kabab_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        Vegetable_Kabab_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Vegetable_Kabab_Price.setForeground(new java.awt.Color(204, 0, 0));
        Vegetable_Kabab_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Vegetable_Kabab_Price.setText("Price = 200Rs.");
        Vegetable_Kabab_Panel.add(Vegetable_Kabab_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        Mutton_Boti_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Mutton_Boti_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mutton_Boti_PannelMouseClicked(evt);
            }
        });
        Mutton_Boti_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mutton_Boti_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Mutton_Boti_Label.setForeground(new java.awt.Color(204, 0, 0));
        Mutton_Boti_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mutton_Boti_Label.setText("Mutton_Boti");
        Mutton_Boti_Pannel.add(Mutton_Boti_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 74, -1));

        Mutton_Boti_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Mutton_Boti_Price.setForeground(new java.awt.Color(204, 0, 0));
        Mutton_Boti_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mutton_Boti_Price.setText("Price = 170Rs.");
        Mutton_Boti_Pannel.add(Mutton_Boti_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        jPanel3.setBackground(new java.awt.Color(102, 255, 204));
        jPanel3.setLayout(null);

        Cash_Remained.setBackground(new java.awt.Color(153, 255, 153));
        Cash_Remained.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cash_Remained.setForeground(new java.awt.Color(204, 0, 0));
        jPanel3.add(Cash_Remained);
        Cash_Remained.setBounds(190, 130, 154, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Rs.");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(350, 90, 33, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Return");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 130, 170, 30);

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Ready for Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(0, 0, 190, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total Price");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 50, 170, 30);

        Total_TextField.setBackground(new java.awt.Color(153, 255, 153));
        Total_TextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Total_TextField.setForeground(new java.awt.Color(204, 0, 0));
        Total_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_TextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(Total_TextField);
        Total_TextField.setBounds(190, 50, 154, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Rs.");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(350, 130, 33, 32);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cash Recieved");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 90, 170, 30);

        Cash_Recieved.setBackground(new java.awt.Color(153, 255, 153));
        Cash_Recieved.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cash_Recieved.setForeground(new java.awt.Color(204, 0, 0));
        Cash_Recieved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cash_RecievedActionPerformed(evt);
            }
        });
        Cash_Recieved.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Cash_RecievedKeyPressed(evt);
            }
        });
        jPanel3.add(Cash_Recieved);
        Cash_Recieved.setBounds(190, 90, 154, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Rs.");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(350, 50, 33, 30);

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Print Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(190, 170, 150, 50);

        Delete_Row.setBackground(new java.awt.Color(153, 255, 153));
        Delete_Row.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Delete_Row.setForeground(new java.awt.Color(204, 0, 0));
        Delete_Row.setText("Delete Some Item/Row");
        Delete_Row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_RowActionPerformed(evt);
            }
        });
        jPanel3.add(Delete_Row);
        Delete_Row.setBounds(270, 0, 190, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(Seekh_Kabab_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(Chicken_Chest_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(Vegetable_Kabab_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(Behari_Kabab_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(Chicken_Boti_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(Malai_Boti_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(Gola_Kabab_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(Chicken_Tikka_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(Reshmi_Kabab_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel16)
                    .addComponent(Mutton_Boti_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(Seekh_Kabab_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6)
                        .addComponent(Chicken_Chest_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel15)
                        .addGap(6, 6, 6)
                        .addComponent(Vegetable_Kabab_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(6, 6, 6)
                        .addComponent(Behari_Kabab_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addComponent(Chicken_Boti_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel16)
                        .addGap(6, 6, 6)
                        .addComponent(Mutton_Boti_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(Malai_Boti_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel13)
                        .addGap(6, 6, 6)
                        .addComponent(Gola_Kabab_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(6, 6, 6)
                        .addComponent(Chicken_Tikka_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel14)
                        .addGap(6, 6, 6)
                        .addComponent(Reshmi_Kabab_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


//Food Types Buttons
    
    
    private void ALL_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALL_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        All_Products all = new All_Products();
        all.Total_Products(this.Total_Amount);
        all.setVisible(true);
        this.dispose();
        all.Import_File();
    }//GEN-LAST:event_ALL_BUTTONActionPerformed

    private void BAR_B_Q_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAR_B_Q_BUTTON1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BAR_B_Q_BUTTON1ActionPerformed

    private void KARAHI_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KARAHI_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        
        KARAHI K = new KARAHI();
        K.setVisible(true);
        K.Total_Karahi(this.Total_Amount);
        this.dispose();
        
        K.Import_File();
        
    }//GEN-LAST:event_KARAHI_BUTTONActionPerformed

    private void RICE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RICE_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        
        RICE rice = new RICE();
        rice.Total_Rice(this.Total_Amount);
        rice.setVisible(true);
        this.dispose();
        rice.Import_File();
        
    }//GEN-LAST:event_RICE_BUTTONActionPerformed

    private void VEGETABLES_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VEGETABLES_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        VEGETABLES vege = new VEGETABLES();
        vege.Total_Vegetables(this.Total_Amount);
        vege.setVisible(true);
        this.dispose();
        vege.Import_File();
    }//GEN-LAST:event_VEGETABLES_BUTTONActionPerformed

    private void BEANS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEANS_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        BEANS beans = new BEANS();
        beans.Total_Beans(this.Total_Amount);
        beans.setVisible(true);
        this.dispose();
        beans.Import_File();
    }//GEN-LAST:event_BEANS_BUTTONActionPerformed

    private void CHINES_DISHES_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHINES_DISHES_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        CHINESE_DISHES china = new CHINESE_DISHES();
        china.Total_Chinese_Dishes(this.Total_Amount);
        china.setVisible(true);
        this.dispose();
        china.Import_File();
    }//GEN-LAST:event_CHINES_DISHES_BUTTONActionPerformed

    private void FAST_FOOD_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAST_FOOD_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        FAST_FOOD fast = new FAST_FOOD();
        fast.Total_Fast_Food(this.Total_Amount);
        fast.setVisible(true);
        this.dispose();
        fast.Import_File();
    }//GEN-LAST:event_FAST_FOOD_BUTTONActionPerformed

    private void SWEETS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SWEETS_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        DESSERTS desserts = new DESSERTS();
        desserts.Total_Desserts(this.Total_Amount);
        desserts.setVisible(true);
        this.dispose();
        desserts.Import_File();
    }//GEN-LAST:event_SWEETS_BUTTONActionPerformed

    private void COLD_DRINKS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COLD_DRINKS_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        BEVERAGES drinks = new BEVERAGES();
        drinks.Total_Drinks(this.Total_Amount);
        drinks.setVisible(true);
        this.dispose();
        drinks.Import_File();
    }//GEN-LAST:event_COLD_DRINKS_BUTTONActionPerformed

    private void TUNDOOR_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUNDOOR_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        TUNDOOR roti = new TUNDOOR();
        roti.Total_Tundoor(this.Total_Amount);
        roti.setVisible(true);
        this.dispose();
        roti.Import_File();
    }//GEN-LAST:event_TUNDOOR_BUTTONActionPerformed

    //Food Type Button Ends
    
    
    
    
    //Click event Starts
    
   
    private void Mutton_Boti_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mutton_Boti_PannelMouseClicked
        // TODO add your handling code here:
        String name = Mutton_Boti_Label.getText();
        int price = 170;
        BBQ(name,price);
        
        
    }//GEN-LAST:event_Mutton_Boti_PannelMouseClicked

    private void Vegetable_Kabab_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Vegetable_Kabab_PanelMouseClicked
        // TODO add your handling code here:
        String name = Vegetable_Kabab_Label.getText();
        int price = 200;
        BBQ(name,price);
    }//GEN-LAST:event_Vegetable_Kabab_PanelMouseClicked

    private void Reshmi_Kabab_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reshmi_Kabab_PannelMouseClicked
        // TODO add your handling code here:
        String name = Reshmi_Kabab_Label.getText();
        int price = 130;
        BBQ(name,price);
    }//GEN-LAST:event_Reshmi_Kabab_PannelMouseClicked

    private void Gola_Kabab_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Gola_Kabab_PannelMouseClicked
        // TODO add your handling code here:
        String name = Gola_Kabab_Label.getText();
        int price = 150;
        BBQ(name,price);
    }//GEN-LAST:event_Gola_Kabab_PannelMouseClicked

    private void Chicken_Boti_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chicken_Boti_PannelMouseClicked
        // TODO add your handling code here:
        String name = Chicken_Boti_Label.getText();
        int price = 150;
        BBQ(name,price);
    }//GEN-LAST:event_Chicken_Boti_PannelMouseClicked

    private void Chicken_Chest_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chicken_Chest_PannelMouseClicked
        // TODO add your handling code here:
        String name = Chicken_Chest_Label.getText();
        int price = 220;
        BBQ(name,price);
    }//GEN-LAST:event_Chicken_Chest_PannelMouseClicked

    private void Chicken_Tikka_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chicken_Tikka_PannelMouseClicked
        // TODO add your handling code here:
        String name = Chicken_Tikka_Label.getText();
        int price = 330;
        BBQ(name,price);
    }//GEN-LAST:event_Chicken_Tikka_PannelMouseClicked

    private void Malai_Boti_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Malai_Boti_PannelMouseClicked
        // TODO add your handling code here:
        String name = Malai_Boti_Label.getText();
        int price = 80;
        BBQ(name,price);
    }//GEN-LAST:event_Malai_Boti_PannelMouseClicked

    private void Seekh_Kabab_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Seekh_Kabab_PannelMouseClicked
        // TODO add your handling code here:
        String name = Seekh_Kabab_Label.getText();
        int price = 80;
        BBQ(name,price);
        
    }//GEN-LAST:event_Seekh_Kabab_PannelMouseClicked

    private void Behari_Kabab_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Behari_Kabab_PannelMouseClicked
        // TODO add your handling code here:
        String name = Behari_Kabab_Label.getText();
        int price = 120;
        BBQ(name,price);
    }//GEN-LAST:event_Behari_Kabab_PannelMouseClicked

    //Click Event ends
    
    
    

//Total Button
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Delete_Row.setEnabled(false);
        Total_TextField.setText("");
        Cash_Recieved.setText("");
        Cash_Remained.setText("");
        
        String Total = Integer.toString(this.Total_Amount);
        Total_TextField.setText(Total);
    }//GEN-LAST:event_jButton1ActionPerformed

    
//Delete Button
    private void Delete_RowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_RowActionPerformed
        // TODO add your handling code here:
        Total_TextField.setText("");
        Cash_Recieved.setText("");
        Cash_Remained.setText("");
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int i = jTable1.getSelectedRow();
        
        
        String Filepath = "E:\\Restaurant-Managememt-System-Java\\Row_Price.txt";
        File file = new File(Filepath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            bw.write(jTable1.getValueAt(i, 3).toString());
            
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Table.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        if(jTable1.getSelectedRow()>=0)
        {
            model.removeRow(jTable1.getSelectedRow());      
        }
        else
        {
            JOptionPane.showMessageDialog(null, "First Select the Row!");
        }

        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);

            Object[] lines = br.lines().toArray();
            String row ="";
            for(int k =0 ; k<lines.length; k++)
            {
                row += lines[k];
            }

            int row_int = 0;
            row_int = Integer.parseInt(row);
            this.Total_Amount -= row_int;
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(KARAHI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
    }//GEN-LAST:event_Delete_RowActionPerformed

    private void Total_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_TextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Total_TextFieldActionPerformed

    private void Cash_RecievedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cash_RecievedKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            
            String Cash = Cash_Recieved.getText();
            int Cash_Int = Integer.parseInt(Cash);

            int Remaining_Int = Cash_Int - this.Total_Amount;
            if(Remaining_Int>0)
            {
                String Remaining = Integer.toString(Remaining_Int);
                Cash_Remained.setText(Remaining);
            }
            
        }
    }//GEN-LAST:event_Cash_RecievedKeyPressed

    private void Cash_RecievedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cash_RecievedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cash_RecievedActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Export_File();
        Bill bill = new Bill();
        bill.Total_Bill(this.Total_Amount,Cash_Recieved.getText(),Cash_Remained.getText());
        bill.setVisible(true);
        bill.Import_File();
    }//GEN-LAST:event_jButton2ActionPerformed
                    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BAR_B_Q_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BAR_B_Q_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BAR_B_Q_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BAR_B_Q_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BAR_B_Q_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ALL_BUTTON;
    private javax.swing.JButton BAR_B_Q_BUTTON1;
    private javax.swing.JButton BEANS_BUTTON;
    private javax.swing.JLabel Behari_Kabab_Label;
    private javax.swing.JPanel Behari_Kabab_Pannel;
    private javax.swing.JLabel Behari_Kabab_Price;
    private javax.swing.JButton CHINES_DISHES_BUTTON;
    private javax.swing.JButton COLD_DRINKS_BUTTON;
    private javax.swing.JTextField Cash_Recieved;
    private javax.swing.JTextField Cash_Remained;
    private javax.swing.JLabel Chicken_Boti_Label;
    private javax.swing.JPanel Chicken_Boti_Pannel;
    private javax.swing.JLabel Chicken_Boti_Price;
    private javax.swing.JLabel Chicken_Chest_Label;
    private javax.swing.JPanel Chicken_Chest_Pannel;
    private javax.swing.JLabel Chicken_Chest_Price;
    private javax.swing.JLabel Chicken_Tikka_Label;
    private javax.swing.JPanel Chicken_Tikka_Pannel;
    private javax.swing.JLabel Chicken_Tikka_Price;
    private javax.swing.JButton Delete_Row;
    private javax.swing.JButton FAST_FOOD_BUTTON;
    private javax.swing.JLabel Gola_Kabab_Label;
    private javax.swing.JPanel Gola_Kabab_Pannel;
    private javax.swing.JLabel Gola_Kabab_Price;
    private javax.swing.JButton KARAHI_BUTTON;
    private javax.swing.JLabel Malai_Boti_Label;
    private javax.swing.JPanel Malai_Boti_Pannel;
    private javax.swing.JLabel Malai_Boti_Price;
    private javax.swing.JLabel Mutton_Boti_Label;
    private javax.swing.JPanel Mutton_Boti_Pannel;
    private javax.swing.JLabel Mutton_Boti_Price;
    private javax.swing.JButton RICE_BUTTON;
    private javax.swing.JLabel Reshmi_Kabab_Label;
    private javax.swing.JPanel Reshmi_Kabab_Pannel;
    private javax.swing.JLabel Reshmi_Kabab_Price;
    private javax.swing.JButton SWEETS_BUTTON;
    private javax.swing.JLabel Seekh_Kabab_Label;
    private javax.swing.JPanel Seekh_Kabab_Pannel;
    private javax.swing.JLabel Seekh_Kabab_Price;
    private javax.swing.JButton TUNDOOR_BUTTON;
    private javax.swing.JTextField Total_TextField;
    private javax.swing.JButton VEGETABLES_BUTTON;
    private javax.swing.JLabel Vegetable_Kabab_Label;
    private javax.swing.JPanel Vegetable_Kabab_Panel;
    private javax.swing.JLabel Vegetable_Kabab_Price;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
