/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhammad Waseem
 */
public class BEVERAGES extends javax.swing.JFrame {

    private int Total_Amount = 0;
    /**
     * Creates new form BEVERAGES
     */
    public BEVERAGES() {
        initComponents();
    }

    
    public void Total_Drinks(int amount)
    {
        this.Total_Amount += amount;
    }
    
    public void Import_File()
    {
        String Filepath = "E:\\Rice.txt";
        File file = new File(Filepath);
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i=0;i<lines.length;i++)
            {
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Table2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void Export_File()
    {
        String Filepath = "E:\\Rice.txt";
        File file = new File(Filepath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i=0;i<jTable1.getRowCount();i++)
            {
                for(int j=0;j<jTable1.getColumnCount();j++)
                {
                    bw.write(jTable1.getValueAt(i, j).toString()+" ");
                }
                bw.newLine();
            }
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Table.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public void Beverages(String name, int price)
    {
        
            
        int Quantity = Integer.parseInt(JOptionPane.showInputDialog(null, "Quantity"));
        if (Quantity > 0) 
        {
            int Total = price * Quantity;
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]
            {
                name,
                price,
                Quantity,
                Total

            });
            this.Total_Amount += Total;
        }
    }
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ALL_BUTTON = new javax.swing.JButton();
        BAR_B_Q_BUTTON1 = new javax.swing.JButton();
        KARAHI_BUTTON = new javax.swing.JButton();
        RICE_BUTTON = new javax.swing.JButton();
        VEGETABLES_BUTTON = new javax.swing.JButton();
        BEANS_BUTTON = new javax.swing.JButton();
        CHINES_DISHES_BUTTON = new javax.swing.JButton();
        FAST_FOOD_BUTTON = new javax.swing.JButton();
        SWEETS_BUTTON = new javax.swing.JButton();
        COLD_DRINKS_BUTTON = new javax.swing.JButton();
        TUNDOOR_BUTTON = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Cold_Drinks_Pannel = new javax.swing.JPanel();
        Cold_Drinks_Label = new javax.swing.JLabel();
        Cold_Drinks_Price = new javax.swing.JLabel();
        Lassi_Pannel = new javax.swing.JPanel();
        Lassi_Label = new javax.swing.JLabel();
        Lassi_Price = new javax.swing.JLabel();
        Cup_of_Tea_Pannel = new javax.swing.JPanel();
        Cup_of_Tea_Label = new javax.swing.JLabel();
        Cup_of_Tea_Price = new javax.swing.JLabel();
        Green_Tea_Pannel = new javax.swing.JPanel();
        Green_Tea_Label = new javax.swing.JLabel();
        Green_Tea_Price = new javax.swing.JLabel();
        Coffee_Pannel = new javax.swing.JPanel();
        Coffee_Label = new javax.swing.JLabel();
        Coffee_Price = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        Cash_Remained = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Total_TextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Cash_Recieved = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Delete_Row = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                formAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ALL_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        ALL_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ALL_BUTTON.setText("ALL PRODUCTS");
        ALL_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALL_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(ALL_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        BAR_B_Q_BUTTON1.setBackground(new java.awt.Color(51, 255, 51));
        BAR_B_Q_BUTTON1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BAR_B_Q_BUTTON1.setText("BAR-B-Q");
        BAR_B_Q_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAR_B_Q_BUTTON1ActionPerformed(evt);
            }
        });
        jPanel2.add(BAR_B_Q_BUTTON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 50));

        KARAHI_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        KARAHI_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        KARAHI_BUTTON.setText("KARAHI");
        KARAHI_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KARAHI_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(KARAHI_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 50));

        RICE_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        RICE_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RICE_BUTTON.setText("RICE");
        RICE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RICE_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(RICE_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 50));

        VEGETABLES_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        VEGETABLES_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        VEGETABLES_BUTTON.setText("VEGETABLES");
        VEGETABLES_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VEGETABLES_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(VEGETABLES_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 50));

        BEANS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        BEANS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BEANS_BUTTON.setText("BEANS");
        BEANS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEANS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(BEANS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 150, 50));

        CHINES_DISHES_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        CHINES_DISHES_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CHINES_DISHES_BUTTON.setText("CHINESE DISHES");
        CHINES_DISHES_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHINES_DISHES_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(CHINES_DISHES_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 150, 50));

        FAST_FOOD_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        FAST_FOOD_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        FAST_FOOD_BUTTON.setText("FAST FOOD");
        FAST_FOOD_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAST_FOOD_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(FAST_FOOD_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 150, 50));

        SWEETS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        SWEETS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SWEETS_BUTTON.setText("SWEETS");
        SWEETS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SWEETS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(SWEETS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 150, 50));

        COLD_DRINKS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        COLD_DRINKS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        COLD_DRINKS_BUTTON.setText("COLD DRINKS");
        COLD_DRINKS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COLD_DRINKS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(COLD_DRINKS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 150, 50));

        TUNDOOR_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        TUNDOOR_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TUNDOOR_BUTTON.setText("FROM TUNDOOR");
        TUNDOOR_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUNDOOR_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(TUNDOOR_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 150, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Beverages/Cold Drinks.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Beverages/Lassi.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Beverages/Tea.jpg"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Beverages/Green Tea.jpg"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Beverages/Coffe.jpg"))); // NOI18N

        Cold_Drinks_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Cold_Drinks_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cold_Drinks_PannelMouseClicked(evt);
            }
        });
        Cold_Drinks_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cold_Drinks_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Cold_Drinks_Label.setForeground(new java.awt.Color(204, 0, 0));
        Cold_Drinks_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cold_Drinks_Label.setText("Cold_Drinks");
        Cold_Drinks_Pannel.add(Cold_Drinks_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, -1));

        Cold_Drinks_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Cold_Drinks_Price.setForeground(new java.awt.Color(204, 0, 0));
        Cold_Drinks_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cold_Drinks_Price.setText("Price = Different Prices");
        Cold_Drinks_Pannel.add(Cold_Drinks_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, -1));

        Lassi_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Lassi_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lassi_PannelMouseClicked(evt);
            }
        });
        Lassi_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lassi_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Lassi_Label.setForeground(new java.awt.Color(204, 0, 0));
        Lassi_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lassi_Label.setText("Lassi");
        Lassi_Pannel.add(Lassi_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        Lassi_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Lassi_Price.setForeground(new java.awt.Color(204, 0, 0));
        Lassi_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lassi_Price.setText("Price = 30Rs.");
        Lassi_Pannel.add(Lassi_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, -1));

        Cup_of_Tea_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Cup_of_Tea_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cup_of_Tea_PannelMouseClicked(evt);
            }
        });
        Cup_of_Tea_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cup_of_Tea_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Cup_of_Tea_Label.setForeground(new java.awt.Color(204, 0, 0));
        Cup_of_Tea_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cup_of_Tea_Label.setText("Cup_of_Tea");
        Cup_of_Tea_Pannel.add(Cup_of_Tea_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 160, -1));

        Cup_of_Tea_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Cup_of_Tea_Price.setForeground(new java.awt.Color(204, 0, 0));
        Cup_of_Tea_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cup_of_Tea_Price.setText("Price = 30Rs.");
        Cup_of_Tea_Pannel.add(Cup_of_Tea_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        Green_Tea_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Green_Tea_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Green_Tea_PannelMouseClicked(evt);
            }
        });
        Green_Tea_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Green_Tea_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Green_Tea_Label.setForeground(new java.awt.Color(204, 0, 0));
        Green_Tea_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Green_Tea_Label.setText("Green_Tea");
        Green_Tea_Pannel.add(Green_Tea_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        Green_Tea_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Green_Tea_Price.setForeground(new java.awt.Color(204, 0, 0));
        Green_Tea_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Green_Tea_Price.setText("Price = 50Rs.");
        Green_Tea_Pannel.add(Green_Tea_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, -1));

        Coffee_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Coffee_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Coffee_PannelMouseClicked(evt);
            }
        });
        Coffee_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Coffee_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Coffee_Label.setForeground(new java.awt.Color(204, 0, 0));
        Coffee_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Coffee_Label.setText("Coffee");
        Coffee_Pannel.add(Coffee_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 10, 120, -1));

        Coffee_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Coffee_Price.setForeground(new java.awt.Color(204, 0, 0));
        Coffee_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Coffee_Price.setText("Price = 100Rs.");
        Coffee_Pannel.add(Coffee_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel4.setBackground(new java.awt.Color(102, 255, 204));
        jPanel4.setLayout(null);

        Cash_Remained.setBackground(new java.awt.Color(153, 255, 153));
        Cash_Remained.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cash_Remained.setForeground(new java.awt.Color(204, 0, 0));
        jPanel4.add(Cash_Remained);
        Cash_Remained.setBounds(190, 130, 154, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Rs.");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(350, 90, 34, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Return");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 130, 170, 30);

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Ready for Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(0, 0, 190, 40);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Total Price");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(10, 50, 170, 30);

        Total_TextField.setBackground(new java.awt.Color(153, 255, 153));
        Total_TextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Total_TextField.setForeground(new java.awt.Color(204, 0, 0));
        Total_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_TextFieldActionPerformed(evt);
            }
        });
        jPanel4.add(Total_TextField);
        Total_TextField.setBounds(190, 50, 154, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("Rs.");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(350, 130, 34, 32);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Cash Recieved");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(10, 90, 170, 30);

        Cash_Recieved.setBackground(new java.awt.Color(153, 255, 153));
        Cash_Recieved.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cash_Recieved.setForeground(new java.awt.Color(204, 0, 0));
        Cash_Recieved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cash_RecievedActionPerformed(evt);
            }
        });
        Cash_Recieved.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Cash_RecievedKeyPressed(evt);
            }
        });
        jPanel4.add(Cash_Recieved);
        Cash_Recieved.setBounds(190, 90, 154, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("Rs.");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(350, 50, 34, 30);

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Print Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(190, 170, 150, 50);

        Delete_Row.setBackground(new java.awt.Color(153, 255, 153));
        Delete_Row.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Delete_Row.setForeground(new java.awt.Color(204, 0, 0));
        Delete_Row.setText("Delete Some Item/Row");
        Delete_Row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_RowActionPerformed(evt);
            }
        });
        jPanel4.add(Delete_Row);
        Delete_Row.setBounds(270, 0, 190, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Coffee_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cold_Drinks_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lassi_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Cup_of_Tea_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Green_Tea_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cold_Drinks_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lassi_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cup_of_Tea_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Green_Tea_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Coffee_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ALL_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALL_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        All_Products all = new All_Products();
        all.Total_Products(this.Total_Amount);
        all.setVisible(true);
        this.dispose();
        all.Import_File();
    }//GEN-LAST:event_ALL_BUTTONActionPerformed

    private void BAR_B_Q_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAR_B_Q_BUTTON1ActionPerformed
        // TODO add your handling code here:
        Export_File();
        BAR_B_Q_Page b = new BAR_B_Q_Page();
        b.Total_BBQ(this.Total_Amount);
        b.setVisible(true);
        this.dispose();
        b.Import_File();
    }//GEN-LAST:event_BAR_B_Q_BUTTON1ActionPerformed

    private void KARAHI_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KARAHI_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        KARAHI K = new KARAHI();
        K.Total_Karahi(this.Total_Amount);
        K.setVisible(true);
        this.dispose();
        K.Import_File();
    }//GEN-LAST:event_KARAHI_BUTTONActionPerformed

    private void RICE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RICE_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        RICE rice = new RICE();
        rice.Total_Rice(this.Total_Amount);
        rice.setVisible(true);
        this.dispose();
        rice.Import_File();
    }//GEN-LAST:event_RICE_BUTTONActionPerformed

    private void VEGETABLES_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VEGETABLES_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        VEGETABLES vege = new VEGETABLES();
        vege.Total_Vegetables(this.Total_Amount);
        vege.setVisible(true);
        this.dispose();
        vege.Import_File();
    }//GEN-LAST:event_VEGETABLES_BUTTONActionPerformed

    private void BEANS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEANS_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        BEANS beans = new BEANS();
        beans.Total_Beans(this.Total_Amount);
        beans.setVisible(true);
        this.dispose();
        beans.Import_File();
    }//GEN-LAST:event_BEANS_BUTTONActionPerformed

    private void CHINES_DISHES_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHINES_DISHES_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        CHINESE_DISHES china = new CHINESE_DISHES();
        china.Total_Chinese_Dishes(this.Total_Amount);
        china.setVisible(true);
        this.dispose();
        china.Import_File();
    }//GEN-LAST:event_CHINES_DISHES_BUTTONActionPerformed

    private void FAST_FOOD_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAST_FOOD_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        FAST_FOOD fast = new FAST_FOOD();
        fast.Total_Fast_Food(this.Total_Amount);
        fast.setVisible(true);
        this.dispose();
        fast.Import_File();
    }//GEN-LAST:event_FAST_FOOD_BUTTONActionPerformed

    private void SWEETS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SWEETS_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        DESSERTS desserts = new DESSERTS();
        desserts.Total_Desserts(this.Total_Amount);
        desserts.setVisible(true);
        this.dispose();
        desserts.Import_File();
    }//GEN-LAST:event_SWEETS_BUTTONActionPerformed

    private void COLD_DRINKS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COLD_DRINKS_BUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COLD_DRINKS_BUTTONActionPerformed

    private void TUNDOOR_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUNDOOR_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        TUNDOOR roti = new TUNDOOR();
        roti.Total_Tundoor(this.Total_Amount);
        roti.setVisible(true);
        this.dispose();
        roti.Import_File();
    }//GEN-LAST:event_TUNDOOR_BUTTONActionPerformed

    
    
    private void Cold_Drinks_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cold_Drinks_PannelMouseClicked
        // TODO add your handling code here:
        String name_drink[] =  {"CocaCola","Pepsi","Sprite","7Up","Dew","Fanta","Marinda"};
        JComboBox cb1 = new JComboBox(name_drink);
        int Input = JOptionPane.showConfirmDialog(rootPane, cb1,"Select Size",JOptionPane.DEFAULT_OPTION);
        
        if(Input == JOptionPane.OK_OPTION)
        {
            String name = (String)cb1.getSelectedItem();
            
            
            
            String size_drink[] =  {"Regular","1/2 Liter","1 Liter","1.5 Liter","2.25 Liter"};
            JComboBox cb2 = new JComboBox(size_drink);
            int Size = JOptionPane.showConfirmDialog(rootPane, cb2,"Select Size",JOptionPane.DEFAULT_OPTION);
        
            if (Size == JOptionPane.OK_OPTION) 
            {
                String size = cb2.getSelectedItem().toString();
                
                if(size == "Regular")
                {
                    int price = 30;
                    Beverages(name,price);
                }
                else if(size == "1/2 Liter")
                {
                    int price = 45;
                    Beverages(name,price);
                }
                else if(size == "1 Liter")
                {
                    int price = 70;
                    Beverages(name,price);
                }
                else if(size == "1.5 Liter")
                {
                    int price = 90;
                    Beverages(name,price);
                }
                else
                {
                    int price = 120;
                    Beverages(name,price);
                }
            }
        }
    }//GEN-LAST:event_Cold_Drinks_PannelMouseClicked

    private void Lassi_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lassi_PannelMouseClicked
        // TODO add your handling code here:
        String name = Lassi_Label.getText();

        int price = 30;
        Beverages(name,price);
    }//GEN-LAST:event_Lassi_PannelMouseClicked

    private void Cup_of_Tea_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cup_of_Tea_PannelMouseClicked
        // TODO add your handling code here:
        String name = Cup_of_Tea_Label.getText();

        int price = 30;
        Beverages(name,price);
    }//GEN-LAST:event_Cup_of_Tea_PannelMouseClicked

    private void Green_Tea_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Green_Tea_PannelMouseClicked
        // TODO add your handling code here:
        String name = Green_Tea_Label.getText();
        int price = 50;
        Beverages(name,price);
    }//GEN-LAST:event_Green_Tea_PannelMouseClicked

    private void Coffee_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Coffee_PannelMouseClicked
        // TODO add your handling code here:
        String name = Coffee_Label.getText();
        int price = 100;
        Beverages(name,price);
    }//GEN-LAST:event_Coffee_PannelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Delete_Row.setEnabled(false);
        Total_TextField.setText("");
        Cash_Recieved.setText("");
        Cash_Remained.setText("");

        String Total = Integer.toString(this.Total_Amount);
        Total_TextField.setText(Total);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Total_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_TextFieldActionPerformed

    private void Cash_RecievedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cash_RecievedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cash_RecievedActionPerformed

    private void Cash_RecievedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cash_RecievedKeyPressed
        // TODO add your handling code here:

        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {

            String Cash = Cash_Recieved.getText();
            int Cash_Int = Integer.parseInt(Cash);
            int Remaining_Int = Cash_Int - this.Total_Amount;
            if (Remaining_Int > 0) 
            {
                String Remaining = Integer.toString(Remaining_Int);
                Cash_Remained.setText(Remaining);
            }

        }
    }//GEN-LAST:event_Cash_RecievedKeyPressed

    private void Delete_RowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_RowActionPerformed
        // TODO add your handling code here:
        Total_TextField.setText("");
        Cash_Recieved.setText("");
        Cash_Remained.setText("");
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int i = jTable1.getSelectedRow();
        
        
        String Filepath = "E:\\Restaurant-Managememt-System-Java\\Row_Price.txt";
        File file = new File(Filepath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            bw.write(jTable1.getValueAt(i, 3).toString());
            
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Table.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        if(jTable1.getSelectedRow()>=0)
        {
            model.removeRow(jTable1.getSelectedRow());      
        }
        else
        {
            JOptionPane.showMessageDialog(null, "First Select the Row!");
        }
        
       try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);

            Object[] lines = br.lines().toArray();
            String row ="";
            for(int k =0 ; k<lines.length; k++)
            {
                row += lines[k];
            }
            int row_int = 0;
            row_int = Integer.parseInt(row);
            this.Total_Amount -= row_int;
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(KARAHI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Delete_RowActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Export_File();
        Bill bill = new Bill();
        bill.Total_Bill(this.Total_Amount,Cash_Recieved.getText(),Cash_Remained.getText());
        bill.setVisible(true);
        bill.Import_File();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorMoved
                                                   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BEVERAGES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BEVERAGES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BEVERAGES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BEVERAGES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BEVERAGES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ALL_BUTTON;
    private javax.swing.JButton BAR_B_Q_BUTTON1;
    private javax.swing.JButton BEANS_BUTTON;
    private javax.swing.JButton CHINES_DISHES_BUTTON;
    private javax.swing.JButton COLD_DRINKS_BUTTON;
    private javax.swing.JTextField Cash_Recieved;
    private javax.swing.JTextField Cash_Remained;
    private javax.swing.JLabel Coffee_Label;
    private javax.swing.JPanel Coffee_Pannel;
    private javax.swing.JLabel Coffee_Price;
    private javax.swing.JLabel Cold_Drinks_Label;
    private javax.swing.JPanel Cold_Drinks_Pannel;
    private javax.swing.JLabel Cold_Drinks_Price;
    private javax.swing.JLabel Cup_of_Tea_Label;
    private javax.swing.JPanel Cup_of_Tea_Pannel;
    private javax.swing.JLabel Cup_of_Tea_Price;
    private javax.swing.JButton Delete_Row;
    private javax.swing.JButton FAST_FOOD_BUTTON;
    private javax.swing.JLabel Green_Tea_Label;
    private javax.swing.JPanel Green_Tea_Pannel;
    private javax.swing.JLabel Green_Tea_Price;
    private javax.swing.JButton KARAHI_BUTTON;
    private javax.swing.JLabel Lassi_Label;
    private javax.swing.JPanel Lassi_Pannel;
    private javax.swing.JLabel Lassi_Price;
    private javax.swing.JButton RICE_BUTTON;
    private javax.swing.JButton SWEETS_BUTTON;
    private javax.swing.JButton TUNDOOR_BUTTON;
    private javax.swing.JTextField Total_TextField;
    private javax.swing.JButton VEGETABLES_BUTTON;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
