/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhammad Waseem
 */
public class CHINESE_DISHES extends javax.swing.JFrame {

    private int Total_Amount = 0;
    /**
     * Creates new form CHINESE_DISHES
     */
    public CHINESE_DISHES() {
        initComponents();
    }

    public void Total_Chinese_Dishes(int amount)
    {
        this.Total_Amount += amount;
    }
    
    
    public void Import_File()
    {
        String Filepath = "E:\\Rice.txt";
        File file = new File(Filepath);
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i=0;i<lines.length;i++)
            {
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Table2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void Export_File()
    {
        String Filepath = "E:\\Rice.txt";
        File file = new File(Filepath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i=0;i<jTable1.getRowCount();i++)
            {
                for(int j=0;j<jTable1.getColumnCount();j++)
                {
                    bw.write(jTable1.getValueAt(i, j).toString()+" ");
                }
                bw.newLine();
            }
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Table.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public void Chinese_Dishes(String name, int price)
    {
        int Quantity = Integer.parseInt(JOptionPane.showInputDialog(null, "Quantity"));
        if (Quantity > 0) 
        {
            int Total = price * Quantity;
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]
            {
                name,
                price,
                Quantity,
                Total

            });
                    this.Total_Amount += Total;
        }
    }
    
 
     /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ALL_BUTTON = new javax.swing.JButton();
        BAR_B_Q_BUTTON1 = new javax.swing.JButton();
        KARAHI_BUTTON = new javax.swing.JButton();
        RICE_BUTTON = new javax.swing.JButton();
        VEGETABLES_BUTTON = new javax.swing.JButton();
        BEANS_BUTTON = new javax.swing.JButton();
        CHINES_DISHES_BUTTON = new javax.swing.JButton();
        FAST_FOOD_BUTTON = new javax.swing.JButton();
        SWEETS_BUTTON = new javax.swing.JButton();
        COLD_DRINKS_BUTTON = new javax.swing.JButton();
        TUNDOOR_BUTTON = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Chow_Mein_Pannel = new javax.swing.JPanel();
        Chow_Mein_Label = new javax.swing.JLabel();
        Chow_Mein_Price = new javax.swing.JLabel();
        Noddle_Soup_Pannel = new javax.swing.JPanel();
        Noddle_Soup_Label = new javax.swing.JLabel();
        Noddle_Soup_Price = new javax.swing.JLabel();
        Fried_Rice_Pannel = new javax.swing.JPanel();
        Fried_Rice_Label = new javax.swing.JLabel();
        Fried_Rice_Price = new javax.swing.JLabel();
        Wonton_Pannel = new javax.swing.JPanel();
        Wonton_Label = new javax.swing.JLabel();
        Wonton_Price = new javax.swing.JLabel();
        Hot_and_Sour_Soup_Pannel = new javax.swing.JPanel();
        Hot_and_Sour_Soup_Label = new javax.swing.JLabel();
        Hot_and_Sour_Soup_Price = new javax.swing.JLabel();
        Manchurian_Pannel = new javax.swing.JPanel();
        Manchurian_Label = new javax.swing.JLabel();
        Manchurian_Price = new javax.swing.JLabel();
        Chilli_Chicken_Pannel = new javax.swing.JPanel();
        Chilli_Chicken_Label = new javax.swing.JLabel();
        Chillil_Chicken_Price = new javax.swing.JLabel();
        Chicken_Vegetable_Spaghetti_Pannel = new javax.swing.JPanel();
        Chicken_Vegetable_Spaghetti_Label = new javax.swing.JLabel();
        Chicken_Vegetable_Spaghetti_Price = new javax.swing.JLabel();
        Dumplings_Pannel = new javax.swing.JPanel();
        Dumplings_Label = new javax.swing.JLabel();
        Dumplings_Price = new javax.swing.JLabel();
        Chicken_Shaslak_Pannel = new javax.swing.JPanel();
        Chicken_Shaslak_Label = new javax.swing.JLabel();
        Chicken_Shaslak_Price = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        Cash_Remained = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Total_TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Cash_Recieved = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Delete_Row = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1371, 735));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ALL_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        ALL_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ALL_BUTTON.setText("ALL PRODUCTS");
        ALL_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALL_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(ALL_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        BAR_B_Q_BUTTON1.setBackground(new java.awt.Color(51, 255, 51));
        BAR_B_Q_BUTTON1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BAR_B_Q_BUTTON1.setText("BAR-B-Q");
        BAR_B_Q_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAR_B_Q_BUTTON1ActionPerformed(evt);
            }
        });
        jPanel2.add(BAR_B_Q_BUTTON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 50));

        KARAHI_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        KARAHI_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        KARAHI_BUTTON.setText("KARAHI");
        KARAHI_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KARAHI_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(KARAHI_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 50));

        RICE_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        RICE_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RICE_BUTTON.setText("RICE");
        RICE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RICE_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(RICE_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 50));

        VEGETABLES_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        VEGETABLES_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        VEGETABLES_BUTTON.setText("VEGETABLES");
        VEGETABLES_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VEGETABLES_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(VEGETABLES_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 50));

        BEANS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        BEANS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BEANS_BUTTON.setText("BEANS");
        BEANS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEANS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(BEANS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 150, 50));

        CHINES_DISHES_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        CHINES_DISHES_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CHINES_DISHES_BUTTON.setText("CHINESE DISHES");
        CHINES_DISHES_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHINES_DISHES_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(CHINES_DISHES_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 150, 50));

        FAST_FOOD_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        FAST_FOOD_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        FAST_FOOD_BUTTON.setText("FAST FOOD");
        FAST_FOOD_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAST_FOOD_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(FAST_FOOD_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 150, 50));

        SWEETS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        SWEETS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SWEETS_BUTTON.setText("DESSERTS");
        SWEETS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SWEETS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(SWEETS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 150, 50));

        COLD_DRINKS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        COLD_DRINKS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        COLD_DRINKS_BUTTON.setText("BEVERAGES");
        COLD_DRINKS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COLD_DRINKS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(COLD_DRINKS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 150, 50));

        TUNDOOR_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        TUNDOOR_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TUNDOOR_BUTTON.setText("FROM TUNDOOR");
        TUNDOOR_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUNDOOR_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(TUNDOOR_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 150, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon("E:\\Restaurant-Managememt-System-Java\\Restaurant-Managememt-System\\src\\login\\Images\\Chinese Dishes\\Chilli Chicken.png")); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon("E:\\Restaurant-Managememt-System-Java\\Restaurant-Managememt-System\\src\\login\\Images\\Chinese Dishes\\Chicken And Vegetable Spaghetti.png")); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon("E:\\Restaurant-Managememt-System-Java\\Restaurant-Managememt-System\\src\\login\\Images\\Chinese Dishes\\Dumplings.png")); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon("E:\\Restaurant-Managememt-System-Java\\Restaurant-Managememt-System\\src\\login\\Images\\Chinese Dishes\\Chicken Shaslick.png")); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\Restaurant-Managememt-System-Java\\Restaurant-Managememt-System\\src\\login\\Images\\Chinese Dishes\\Chow mein.png")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\Restaurant-Managememt-System-Java\\Restaurant-Managememt-System\\src\\login\\Images\\Chinese Dishes\\Noddle Soup.png")); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon("E:\\Restaurant-Managememt-System-Java\\Restaurant-Managememt-System\\src\\login\\Images\\Chinese Dishes\\Fried Rice.png")); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon("E:\\Restaurant-Managememt-System-Java\\Restaurant-Managememt-System\\src\\login\\Images\\Chinese Dishes\\Wonton.png")); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon("E:\\Restaurant-Managememt-System-Java\\Restaurant-Managememt-System\\src\\login\\Images\\Chinese Dishes\\Hot and Sour Soup.png")); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon("E:\\Restaurant-Managememt-System-Java\\Restaurant-Managememt-System\\src\\login\\Images\\Chinese Dishes\\Manchurian.png")); // NOI18N

        Chow_Mein_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Chow_Mein_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chow_Mein_PannelMouseClicked(evt);
            }
        });
        Chow_Mein_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Chow_Mein_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chow_Mein_Label.setForeground(new java.awt.Color(204, 0, 0));
        Chow_Mein_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chow_Mein_Label.setText("Chow_Mein");
        Chow_Mein_Pannel.add(Chow_Mein_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, -1));

        Chow_Mein_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chow_Mein_Price.setForeground(new java.awt.Color(204, 0, 0));
        Chow_Mein_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chow_Mein_Price.setText("Price = 250Rs.");
        Chow_Mein_Pannel.add(Chow_Mein_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, -1));

        Noddle_Soup_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Noddle_Soup_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Noddle_Soup_PannelMouseClicked(evt);
            }
        });
        Noddle_Soup_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Noddle_Soup_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Noddle_Soup_Label.setForeground(new java.awt.Color(204, 0, 0));
        Noddle_Soup_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Noddle_Soup_Label.setText("Noddle_Soup");
        Noddle_Soup_Pannel.add(Noddle_Soup_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        Noddle_Soup_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Noddle_Soup_Price.setForeground(new java.awt.Color(204, 0, 0));
        Noddle_Soup_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Noddle_Soup_Price.setText("Price = 120Rs.");
        Noddle_Soup_Pannel.add(Noddle_Soup_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        Fried_Rice_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Fried_Rice_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Fried_Rice_PannelMouseClicked(evt);
            }
        });
        Fried_Rice_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fried_Rice_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Fried_Rice_Label.setForeground(new java.awt.Color(204, 0, 0));
        Fried_Rice_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fried_Rice_Label.setText("Fried_Rice");
        Fried_Rice_Pannel.add(Fried_Rice_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, 90, -1));

        Fried_Rice_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Fried_Rice_Price.setForeground(new java.awt.Color(204, 0, 0));
        Fried_Rice_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fried_Rice_Price.setText("Price = 150Rs.");
        Fried_Rice_Pannel.add(Fried_Rice_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        Wonton_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Wonton_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Wonton_PannelMouseClicked(evt);
            }
        });
        Wonton_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Wonton_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Wonton_Label.setForeground(new java.awt.Color(204, 0, 0));
        Wonton_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Wonton_Label.setText("Wonton");
        Wonton_Pannel.add(Wonton_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 80, -1));

        Wonton_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Wonton_Price.setForeground(new java.awt.Color(204, 0, 0));
        Wonton_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Wonton_Price.setText("Price = 250Rs./dozen");
        Wonton_Pannel.add(Wonton_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, -1));

        Hot_and_Sour_Soup_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Hot_and_Sour_Soup_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Hot_and_Sour_Soup_PannelMouseClicked(evt);
            }
        });
        Hot_and_Sour_Soup_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hot_and_Sour_Soup_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Hot_and_Sour_Soup_Label.setForeground(new java.awt.Color(204, 0, 0));
        Hot_and_Sour_Soup_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hot_and_Sour_Soup_Label.setText("Hot_and_Sour_Soup");
        Hot_and_Sour_Soup_Pannel.add(Hot_and_Sour_Soup_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, -1));

        Hot_and_Sour_Soup_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Hot_and_Sour_Soup_Price.setForeground(new java.awt.Color(204, 0, 0));
        Hot_and_Sour_Soup_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hot_and_Sour_Soup_Price.setText("Price = 150Rs.");
        Hot_and_Sour_Soup_Pannel.add(Hot_and_Sour_Soup_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        Manchurian_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Manchurian_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Manchurian_PannelMouseClicked(evt);
            }
        });
        Manchurian_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Manchurian_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Manchurian_Label.setForeground(new java.awt.Color(204, 0, 0));
        Manchurian_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Manchurian_Label.setText("Manchurian");
        Manchurian_Pannel.add(Manchurian_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 74, -1));

        Manchurian_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Manchurian_Price.setForeground(new java.awt.Color(204, 0, 0));
        Manchurian_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Manchurian_Price.setText("Price = 325Rs.");
        Manchurian_Pannel.add(Manchurian_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        Chilli_Chicken_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Chilli_Chicken_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chilli_Chicken_PannelMouseClicked(evt);
            }
        });
        Chilli_Chicken_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Chilli_Chicken_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chilli_Chicken_Label.setForeground(new java.awt.Color(204, 0, 0));
        Chilli_Chicken_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chilli_Chicken_Label.setText("Chilli_Chicken");
        Chilli_Chicken_Pannel.add(Chilli_Chicken_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, -1));

        Chillil_Chicken_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chillil_Chicken_Price.setForeground(new java.awt.Color(204, 0, 0));
        Chillil_Chicken_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chillil_Chicken_Price.setText("Price = 250Rs.");
        Chilli_Chicken_Pannel.add(Chillil_Chicken_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        Chicken_Vegetable_Spaghetti_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Chicken_Vegetable_Spaghetti_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chicken_Vegetable_Spaghetti_PannelMouseClicked(evt);
            }
        });
        Chicken_Vegetable_Spaghetti_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Chicken_Vegetable_Spaghetti_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chicken_Vegetable_Spaghetti_Label.setForeground(new java.awt.Color(204, 0, 0));
        Chicken_Vegetable_Spaghetti_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken_Vegetable_Spaghetti_Label.setText("Chicken_Vegetable_Spaghetti");
        Chicken_Vegetable_Spaghetti_Pannel.add(Chicken_Vegetable_Spaghetti_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 10, 160, -1));

        Chicken_Vegetable_Spaghetti_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chicken_Vegetable_Spaghetti_Price.setForeground(new java.awt.Color(204, 0, 0));
        Chicken_Vegetable_Spaghetti_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken_Vegetable_Spaghetti_Price.setText("Price = 325Rs.");
        Chicken_Vegetable_Spaghetti_Pannel.add(Chicken_Vegetable_Spaghetti_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        Dumplings_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Dumplings_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dumplings_PannelMouseClicked(evt);
            }
        });
        Dumplings_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dumplings_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Dumplings_Label.setForeground(new java.awt.Color(204, 0, 0));
        Dumplings_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dumplings_Label.setText("Dumplings");
        Dumplings_Pannel.add(Dumplings_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 10, 120, -1));

        Dumplings_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Dumplings_Price.setForeground(new java.awt.Color(204, 0, 0));
        Dumplings_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dumplings_Price.setText("Price = 50Rs./piece");
        Dumplings_Pannel.add(Dumplings_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, -1));

        Chicken_Shaslak_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Chicken_Shaslak_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chicken_Shaslak_PannelMouseClicked(evt);
            }
        });
        Chicken_Shaslak_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Chicken_Shaslak_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chicken_Shaslak_Label.setForeground(new java.awt.Color(204, 0, 0));
        Chicken_Shaslak_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken_Shaslak_Label.setText("Chicken_Shaslak");
        Chicken_Shaslak_Pannel.add(Chicken_Shaslak_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, -1));

        Chicken_Shaslak_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chicken_Shaslak_Price.setForeground(new java.awt.Color(204, 0, 0));
        Chicken_Shaslak_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken_Shaslak_Price.setText("Price = 350Rs.");
        Chicken_Shaslak_Pannel.add(Chicken_Shaslak_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel3.setBackground(new java.awt.Color(102, 255, 204));
        jPanel3.setLayout(null);

        Cash_Remained.setBackground(new java.awt.Color(153, 255, 153));
        Cash_Remained.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cash_Remained.setForeground(new java.awt.Color(204, 0, 0));
        jPanel3.add(Cash_Remained);
        Cash_Remained.setBounds(190, 130, 154, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Rs.");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(350, 90, 34, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Return");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 130, 170, 30);

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Ready for Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(0, 0, 190, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total Price");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 50, 170, 30);

        Total_TextField.setBackground(new java.awt.Color(153, 255, 153));
        Total_TextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Total_TextField.setForeground(new java.awt.Color(204, 0, 0));
        Total_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_TextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(Total_TextField);
        Total_TextField.setBounds(190, 50, 154, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Rs.");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(350, 130, 34, 32);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cash Recieved");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 90, 170, 30);

        Cash_Recieved.setBackground(new java.awt.Color(153, 255, 153));
        Cash_Recieved.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cash_Recieved.setForeground(new java.awt.Color(204, 0, 0));
        Cash_Recieved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cash_RecievedActionPerformed(evt);
            }
        });
        Cash_Recieved.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Cash_RecievedKeyPressed(evt);
            }
        });
        jPanel3.add(Cash_Recieved);
        Cash_Recieved.setBounds(190, 90, 154, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Rs.");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(350, 50, 34, 30);

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Print Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(190, 170, 150, 50);

        Delete_Row.setBackground(new java.awt.Color(153, 255, 153));
        Delete_Row.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Delete_Row.setForeground(new java.awt.Color(204, 0, 0));
        Delete_Row.setText("Delete Some Item/Row");
        Delete_Row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_RowActionPerformed(evt);
            }
        });
        jPanel3.add(Delete_Row);
        Delete_Row.setBounds(270, 0, 190, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Chow_Mein_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hot_and_Sour_Soup_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Noddle_Soup_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Fried_Rice_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Wonton_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Manchurian_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Chilli_Chicken_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Chicken_Vegetable_Spaghetti_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Dumplings_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Chicken_Shaslak_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Chow_Mein_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Noddle_Soup_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Fried_Rice_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Wonton_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Manchurian_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Hot_and_Sour_Soup_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Chicken_Vegetable_Spaghetti_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Chilli_Chicken_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Chicken_Shaslak_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Dumplings_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ALL_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALL_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        All_Products all = new All_Products();
        all.Total_Products(this.Total_Amount);
        all.setVisible(true);
        this.dispose();
        all.Import_File();
    }//GEN-LAST:event_ALL_BUTTONActionPerformed

    private void BAR_B_Q_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAR_B_Q_BUTTON1ActionPerformed
        // TODO add your handling code here:
        Export_File();
        BAR_B_Q_Page b = new BAR_B_Q_Page();
        b.Total_BBQ(this.Total_Amount);
        b.setVisible(true);
        this.dispose();
        b.Import_File();
    }//GEN-LAST:event_BAR_B_Q_BUTTON1ActionPerformed

    private void KARAHI_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KARAHI_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        KARAHI K =new KARAHI();
        K.Total_Karahi(this.Total_Amount);
        K.setVisible(true);
        this.dispose();
        K.Import_File();
    }//GEN-LAST:event_KARAHI_BUTTONActionPerformed

    private void RICE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RICE_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        RICE rice = new RICE();
        rice.Total_Rice(this.Total_Amount);
        rice.setVisible(true);
        this.dispose();
        rice.Import_File();
    }//GEN-LAST:event_RICE_BUTTONActionPerformed

    private void VEGETABLES_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VEGETABLES_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        VEGETABLES vege = new VEGETABLES();
        vege.Total_Vegetables(this.Total_Amount);
        vege.setVisible(true);
        this.dispose();
        vege.Import_File();
    }//GEN-LAST:event_VEGETABLES_BUTTONActionPerformed

    private void BEANS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEANS_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        BEANS beans = new BEANS();
        beans.Total_Beans(this.Total_Amount);
        beans.setVisible(true);
        this.dispose();
        beans.Import_File();
    }//GEN-LAST:event_BEANS_BUTTONActionPerformed

    private void CHINES_DISHES_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHINES_DISHES_BUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHINES_DISHES_BUTTONActionPerformed

    private void FAST_FOOD_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAST_FOOD_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        FAST_FOOD fast = new FAST_FOOD();
        fast.Total_Fast_Food(this.Total_Amount);
        fast.setVisible(true);
        this.dispose();
        fast.Import_File();
    }//GEN-LAST:event_FAST_FOOD_BUTTONActionPerformed

    private void SWEETS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SWEETS_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        DESSERTS desserts = new DESSERTS();
        desserts.Total_Desserts(this.Total_Amount);
        desserts.setVisible(true);
        this.dispose();
        desserts.Import_File();
    }//GEN-LAST:event_SWEETS_BUTTONActionPerformed

    private void COLD_DRINKS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COLD_DRINKS_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        BEVERAGES drinks = new BEVERAGES();
        drinks.Total_Drinks(this.Total_Amount);
        drinks.setVisible(true);
        this.dispose();
        drinks.Import_File();
    }//GEN-LAST:event_COLD_DRINKS_BUTTONActionPerformed

    private void TUNDOOR_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUNDOOR_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        TUNDOOR roti = new TUNDOOR();
        roti.Total_Tundoor(this.Total_Amount);
        roti.setVisible(true);
        this.dispose();
        roti.Import_File();
    }//GEN-LAST:event_TUNDOOR_BUTTONActionPerformed

    
    private void Chow_Mein_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chow_Mein_PannelMouseClicked
        // TODO add your handling code here:
        String name = Chow_Mein_Label.getText();

        int price = 250;
        Chinese_Dishes(name,price);
    }//GEN-LAST:event_Chow_Mein_PannelMouseClicked

    private void Noddle_Soup_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Noddle_Soup_PannelMouseClicked
        // TODO add your handling code here:
        String name = Noddle_Soup_Label.getText();

        int price = 120;
        Chinese_Dishes(name,price);

    }//GEN-LAST:event_Noddle_Soup_PannelMouseClicked

    private void Fried_Rice_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fried_Rice_PannelMouseClicked
        // TODO add your handling code here:
        String name = Fried_Rice_Label.getText();

        int price = 150;
        Chinese_Dishes(name,price);

    }//GEN-LAST:event_Fried_Rice_PannelMouseClicked

    private void Wonton_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Wonton_PannelMouseClicked
        // TODO add your handling code here:
        String name = Wonton_Label.getText();
        int price = 250;
        Chinese_Dishes(name,price);
    }//GEN-LAST:event_Wonton_PannelMouseClicked

    private void Hot_and_Sour_Soup_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hot_and_Sour_Soup_PannelMouseClicked
        // TODO add your handling code here:
        String name = Hot_and_Sour_Soup_Label.getText();
        int price = 150;
        Chinese_Dishes(name,price);
    }//GEN-LAST:event_Hot_and_Sour_Soup_PannelMouseClicked

    private void Manchurian_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Manchurian_PannelMouseClicked
        // TODO add your handling code here:
        String name = Manchurian_Label.getText();
        int price = 325;
        Chinese_Dishes(name,price);

    }//GEN-LAST:event_Manchurian_PannelMouseClicked

    private void Chilli_Chicken_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chilli_Chicken_PannelMouseClicked
        // TODO add your handling code here:
        String name = Chilli_Chicken_Label.getText();
        int price = 250;
        Chinese_Dishes(name,price);
    }//GEN-LAST:event_Chilli_Chicken_PannelMouseClicked

    private void Chicken_Vegetable_Spaghetti_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chicken_Vegetable_Spaghetti_PannelMouseClicked
        // TODO add your handling code here:
        String name = Chicken_Vegetable_Spaghetti_Label.getText();
        int price = 325;
        Chinese_Dishes(name,price);
    }//GEN-LAST:event_Chicken_Vegetable_Spaghetti_PannelMouseClicked

    private void Dumplings_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dumplings_PannelMouseClicked
        // TODO add your handling code here:
        String name = Dumplings_Label.getText();
        int price = 50;
        Chinese_Dishes(name,price);
    }//GEN-LAST:event_Dumplings_PannelMouseClicked

    private void Chicken_Shaslak_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chicken_Shaslak_PannelMouseClicked
        // TODO add your handling code here:
        String name = Chicken_Shaslak_Label.getText();
        int price = 350;
        Chinese_Dishes(name,price);
    }//GEN-LAST:event_Chicken_Shaslak_PannelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Delete_Row.setEnabled(false);
        Total_TextField.setText("");
        Cash_Recieved.setText("");
        Cash_Remained.setText("");

        String Total = Integer.toString(this.Total_Amount);
        Total_TextField.setText(Total);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Total_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_TextFieldActionPerformed

    private void Cash_RecievedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cash_RecievedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cash_RecievedActionPerformed

    private void Cash_RecievedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cash_RecievedKeyPressed
        // TODO add your handling code here:

        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {

            String Cash = Cash_Recieved.getText();
            int Cash_Int = Integer.parseInt(Cash);
            int Remaining_Int = Cash_Int - this.Total_Amount;
            if (Remaining_Int > 0) 
            {
                String Remaining = Integer.toString(Remaining_Int);
                Cash_Remained.setText(Remaining);
            }

        }
    }//GEN-LAST:event_Cash_RecievedKeyPressed

    private void Delete_RowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_RowActionPerformed
        // TODO add your handling code here:
        Total_TextField.setText("");
        Cash_Recieved.setText("");
        Cash_Remained.setText("");
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int i = jTable1.getSelectedRow();
        
        
        String Filepath = "E:\\Restaurant-Managememt-System-Java\\Row_Price.txt";
        File file = new File(Filepath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            bw.write(jTable1.getValueAt(i, 3).toString());
            
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Table.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        if(jTable1.getSelectedRow()>=0)
        {
            model.removeRow(jTable1.getSelectedRow());      
        }
        else
        {
            JOptionPane.showMessageDialog(null, "First Select the Row!");
        }
        
       try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);

            Object[] lines = br.lines().toArray();
            String row ="";
            for(int k =0 ; k<lines.length; k++)
            {
                row += lines[k];
            }
            int row_int = 0;
            row_int = Integer.parseInt(row);
            this.Total_Amount -= row_int;
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(KARAHI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Delete_RowActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Export_File();
        Bill bill = new Bill();
        bill.Total_Bill(this.Total_Amount,Cash_Recieved.getText(),Cash_Remained.getText());
        bill.setVisible(true);
        bill.Import_File();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHINESE_DISHES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHINESE_DISHES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHINESE_DISHES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHINESE_DISHES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CHINESE_DISHES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ALL_BUTTON;
    private javax.swing.JButton BAR_B_Q_BUTTON1;
    private javax.swing.JButton BEANS_BUTTON;
    private javax.swing.JButton CHINES_DISHES_BUTTON;
    private javax.swing.JButton COLD_DRINKS_BUTTON;
    private javax.swing.JTextField Cash_Recieved;
    private javax.swing.JTextField Cash_Remained;
    private javax.swing.JLabel Chicken_Shaslak_Label;
    private javax.swing.JPanel Chicken_Shaslak_Pannel;
    private javax.swing.JLabel Chicken_Shaslak_Price;
    private javax.swing.JLabel Chicken_Vegetable_Spaghetti_Label;
    private javax.swing.JPanel Chicken_Vegetable_Spaghetti_Pannel;
    private javax.swing.JLabel Chicken_Vegetable_Spaghetti_Price;
    private javax.swing.JLabel Chilli_Chicken_Label;
    private javax.swing.JPanel Chilli_Chicken_Pannel;
    private javax.swing.JLabel Chillil_Chicken_Price;
    private javax.swing.JLabel Chow_Mein_Label;
    private javax.swing.JPanel Chow_Mein_Pannel;
    private javax.swing.JLabel Chow_Mein_Price;
    private javax.swing.JButton Delete_Row;
    private javax.swing.JLabel Dumplings_Label;
    private javax.swing.JPanel Dumplings_Pannel;
    private javax.swing.JLabel Dumplings_Price;
    private javax.swing.JButton FAST_FOOD_BUTTON;
    private javax.swing.JLabel Fried_Rice_Label;
    private javax.swing.JPanel Fried_Rice_Pannel;
    private javax.swing.JLabel Fried_Rice_Price;
    private javax.swing.JLabel Hot_and_Sour_Soup_Label;
    private javax.swing.JPanel Hot_and_Sour_Soup_Pannel;
    private javax.swing.JLabel Hot_and_Sour_Soup_Price;
    private javax.swing.JButton KARAHI_BUTTON;
    private javax.swing.JLabel Manchurian_Label;
    private javax.swing.JPanel Manchurian_Pannel;
    private javax.swing.JLabel Manchurian_Price;
    private javax.swing.JLabel Noddle_Soup_Label;
    private javax.swing.JPanel Noddle_Soup_Pannel;
    private javax.swing.JLabel Noddle_Soup_Price;
    private javax.swing.JButton RICE_BUTTON;
    private javax.swing.JButton SWEETS_BUTTON;
    private javax.swing.JButton TUNDOOR_BUTTON;
    private javax.swing.JTextField Total_TextField;
    private javax.swing.JButton VEGETABLES_BUTTON;
    private javax.swing.JLabel Wonton_Label;
    private javax.swing.JPanel Wonton_Pannel;
    private javax.swing.JLabel Wonton_Price;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
