/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import javax.swing.JOptionPane;


/**
 *
 * @author Muhammad Waseem
 */
public class Customer_Tables extends javax.swing.JFrame {

    private String Customer_Table;
    private int Number_of_People = 0;
    /**
     * Creates new form Customer_Tables
     */
    public Customer_Tables() {
        initComponents();
    }

    public void set_Table()
    {
        this.Customer_Table = this.Customer_Table;
    }
    public String get_Table()
    {
        return this.Customer_Table;
    }

    public void Table_Selection_Function(int number)
    {
        this.Number_of_People += number;
        
        
        if(this.Number_of_People == 1)
        {
            Double_Sitter1.setVisible(false);
            Double_Sitter2.setVisible(false);
            Double_Sitter3.setVisible(false);
            Fourth_Sitter1.setVisible(false);
            Fourth_Sitter2.setVisible(false);
            Fourth_Sitter3.setVisible(false);
            Extra_Sitter1.setVisible(false);
            Extra_Sitter2.setVisible(false);
            Extra_Sitter3.setVisible(false);
            Extra_Sitter4.setVisible(false);
            Extra_Sitter5.setVisible(false);
                                  
            
        }
        else if(this.Number_of_People == 2)
        {
            Single_Sitter1.setVisible(false);
            Single_Sitter2.setVisible(false);
            Single_Sitter3.setVisible(false);
            Fourth_Sitter1.setVisible(false);
            Fourth_Sitter2.setVisible(false);
            Fourth_Sitter3.setVisible(false);
            Extra_Sitter1.setVisible(false);
            Extra_Sitter2.setVisible(false);
            Extra_Sitter3.setVisible(false);
            Extra_Sitter4.setVisible(false);
            Extra_Sitter5.setVisible(false);
            
            
        }
        else if(this.Number_of_People == 4 || this.Number_of_People == 3)
        {
            Single_Sitter1.setVisible(false);
            Single_Sitter2.setVisible(false);
            Single_Sitter3.setVisible(false);
            Double_Sitter1.setVisible(false);
            Double_Sitter2.setVisible(false);
            Double_Sitter3.setVisible(false);
            Extra_Sitter1.setVisible(false);
            Extra_Sitter2.setVisible(false);
            Extra_Sitter3.setVisible(false);
            Extra_Sitter4.setVisible(false);
            Extra_Sitter5.setVisible(false);
            
            
        }
        else if(this.Number_of_People >= 5)
        {
            Single_Sitter1.setVisible(false);
            Single_Sitter2.setVisible(false);
            Single_Sitter3.setVisible(false);
            Double_Sitter1.setVisible(false);
            Double_Sitter2.setVisible(false);
            Double_Sitter3.setVisible(false);
            Fourth_Sitter1.setVisible(false);
            Fourth_Sitter2.setVisible(false);
            Fourth_Sitter3.setVisible(false);
            
            
        }
        
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Please Select the Table Number");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        People_Label = new javax.swing.JLabel();
        Next_Button = new keeptoo.KButton();
        Single_Sitter1 = new javax.swing.JRadioButton();
        Single_Sitter2 = new javax.swing.JRadioButton();
        Single_Sitter3 = new javax.swing.JRadioButton();
        Double_Sitter1 = new javax.swing.JRadioButton();
        Double_Sitter2 = new javax.swing.JRadioButton();
        Double_Sitter3 = new javax.swing.JRadioButton();
        Fourth_Sitter1 = new javax.swing.JRadioButton();
        Fourth_Sitter2 = new javax.swing.JRadioButton();
        Fourth_Sitter3 = new javax.swing.JRadioButton();
        Extra_Sitter1 = new javax.swing.JRadioButton();
        Extra_Sitter2 = new javax.swing.JRadioButton();
        Extra_Sitter3 = new javax.swing.JRadioButton();
        Extra_Sitter4 = new javax.swing.JRadioButton();
        Extra_Sitter5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kGradientPanel2.setkEndColor(new java.awt.Color(0, 255, 0));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 153, 153));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        People_Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        People_Label.setForeground(new java.awt.Color(255, 255, 255));
        People_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        People_Label.setText("Select the Table");
        People_Label.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kGradientPanel2.add(People_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 100));

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 410, 100));

        Next_Button.setText("Next");
        Next_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Next_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_ButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Next_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 130, 60));

        buttonGroup1.add(Single_Sitter1);
        Single_Sitter1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Single_Sitter1.setText("Table 1");
        kGradientPanel1.add(Single_Sitter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        buttonGroup1.add(Single_Sitter2);
        Single_Sitter2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Single_Sitter2.setText("Table 2");
        kGradientPanel1.add(Single_Sitter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        buttonGroup1.add(Single_Sitter3);
        Single_Sitter3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Single_Sitter3.setText("Table 3");
        kGradientPanel1.add(Single_Sitter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        buttonGroup1.add(Double_Sitter1);
        Double_Sitter1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Double_Sitter1.setText("Table 4");
        kGradientPanel1.add(Double_Sitter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        buttonGroup1.add(Double_Sitter2);
        Double_Sitter2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Double_Sitter2.setText("Table 5");
        kGradientPanel1.add(Double_Sitter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        buttonGroup1.add(Double_Sitter3);
        Double_Sitter3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Double_Sitter3.setText("Table 6");
        kGradientPanel1.add(Double_Sitter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        buttonGroup1.add(Fourth_Sitter1);
        Fourth_Sitter1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Fourth_Sitter1.setText("Table 7");
        kGradientPanel1.add(Fourth_Sitter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        buttonGroup1.add(Fourth_Sitter2);
        Fourth_Sitter2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Fourth_Sitter2.setText("Table 8");
        kGradientPanel1.add(Fourth_Sitter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        buttonGroup1.add(Fourth_Sitter3);
        Fourth_Sitter3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Fourth_Sitter3.setText("Table 9");
        kGradientPanel1.add(Fourth_Sitter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        buttonGroup1.add(Extra_Sitter1);
        Extra_Sitter1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Extra_Sitter1.setText("Table 10");
        kGradientPanel1.add(Extra_Sitter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        buttonGroup1.add(Extra_Sitter2);
        Extra_Sitter2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Extra_Sitter2.setText("Table 11");
        kGradientPanel1.add(Extra_Sitter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        buttonGroup1.add(Extra_Sitter3);
        Extra_Sitter3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Extra_Sitter3.setText("Table 12");
        kGradientPanel1.add(Extra_Sitter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        buttonGroup1.add(Extra_Sitter4);
        Extra_Sitter4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Extra_Sitter4.setText("Table 13");
        kGradientPanel1.add(Extra_Sitter4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        buttonGroup1.add(Extra_Sitter5);
        Extra_Sitter5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Extra_Sitter5.setText("Table 14");
        Extra_Sitter5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Extra_Sitter5ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Extra_Sitter5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Next_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_ButtonActionPerformed
        // TODO add your handling code here:
        if (Single_Sitter1.isSelected() == true) {
            JOptionPane.showMessageDialog(rootPane, "Your Table No is : " + Single_Sitter1.getText());
            this.Customer_Table  = Single_Sitter1.getText();
        } else if (Single_Sitter2.isSelected() == true) {
            JOptionPane.showMessageDialog(rootPane, "Your Table No is : " + Single_Sitter2.getText());
            this.Customer_Table  = Single_Sitter2.getText();
        } else if (Single_Sitter3.isSelected() == true) {
            JOptionPane.showMessageDialog(rootPane, "Your Table No is : " + Single_Sitter3.getText());
            this.Customer_Table  = Single_Sitter3.getText();
        } else if (Double_Sitter1.isSelected() == true) {
            JOptionPane.showMessageDialog(rootPane, "Your Table No is : " + Double_Sitter1.getText());
            this.Customer_Table  = Double_Sitter1.getText();
        } else if (Double_Sitter2.isSelected() == true) {
            JOptionPane.showMessageDialog(rootPane, "Your Table No is : " + Double_Sitter2.getText());
            this.Customer_Table  = Double_Sitter2.getText();
        } else if (Double_Sitter3.isSelected() == true) {
            JOptionPane.showMessageDialog(rootPane, "Your Table No is : " + Double_Sitter3.getText());
            this.Customer_Table  = Double_Sitter3.getText();
        }
          else if (Fourth_Sitter1.isSelected() == true) {
            JOptionPane.showMessageDialog(rootPane, "Your Table No is : " + Fourth_Sitter1.getText());
            this.Customer_Table  = Fourth_Sitter1.getText();
        } else if (Fourth_Sitter2.isSelected() == true) {
            JOptionPane.showMessageDialog(rootPane, "Your Table No is : " + Fourth_Sitter2.getText());
            this.Customer_Table  = Fourth_Sitter2.getText();
        } else if (Fourth_Sitter3.isSelected() == true) {
            JOptionPane.showMessageDialog(rootPane, "Your Table No is : " + Fourth_Sitter3.getText());
            this.Customer_Table  = Fourth_Sitter3.getText();
        }
          else if (Extra_Sitter1.isSelected() == true) {
            JOptionPane.showMessageDialog(rootPane, "Your Table No is : " + Extra_Sitter1.getText());
            this.Customer_Table  = Extra_Sitter1.getText();
        } else if (Extra_Sitter2.isSelected() == true) {
            JOptionPane.showMessageDialog(rootPane, "Your Table No is : " + Extra_Sitter2.getText());
            this.Customer_Table  = Extra_Sitter2.getText();
        } else if (Extra_Sitter3.isSelected() == true) {
            JOptionPane.showMessageDialog(rootPane, "Your Table No is : " + Extra_Sitter3.getText());
            this.Customer_Table  = Extra_Sitter3.getText();
        } else if (Extra_Sitter4.isSelected() == true) {
            JOptionPane.showMessageDialog(rootPane, "Your Table No is : " + Extra_Sitter4.getText());
            this.Customer_Table  = Extra_Sitter4.getText();
        } else if (Extra_Sitter5.isSelected() == true) {
            JOptionPane.showMessageDialog(rootPane, "Your Table No is : " + Extra_Sitter5.getText());
            this.Customer_Table  = Extra_Sitter5.getText();
        }
        
        
        Table_Selection_Function(this.Number_of_People);
        All_Products all = new All_Products();
        all.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_Next_ButtonActionPerformed

    private void Extra_Sitter5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Extra_Sitter5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Extra_Sitter5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Tables().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Double_Sitter1;
    private javax.swing.JRadioButton Double_Sitter2;
    private javax.swing.JRadioButton Double_Sitter3;
    private javax.swing.JRadioButton Extra_Sitter1;
    private javax.swing.JRadioButton Extra_Sitter2;
    private javax.swing.JRadioButton Extra_Sitter3;
    private javax.swing.JRadioButton Extra_Sitter4;
    private javax.swing.JRadioButton Extra_Sitter5;
    private javax.swing.JRadioButton Fourth_Sitter1;
    private javax.swing.JRadioButton Fourth_Sitter2;
    private javax.swing.JRadioButton Fourth_Sitter3;
    private keeptoo.KButton Next_Button;
    private javax.swing.JLabel People_Label;
    private javax.swing.JRadioButton Single_Sitter1;
    private javax.swing.JRadioButton Single_Sitter2;
    private javax.swing.JRadioButton Single_Sitter3;
    private javax.swing.ButtonGroup buttonGroup1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
