/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Waseem
 */
public class Dine_in extends javax.swing.JFrame {

    /**
     * Creates new form Dine_in
     */
    public Dine_in() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        People_Label = new javax.swing.JLabel();
        No_of_People_Field = new javax.swing.JTextField();
        Next_Button = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kGradientPanel2.setkEndColor(new java.awt.Color(0, 255, 0));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 153, 153));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        People_Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        People_Label.setForeground(new java.awt.Color(255, 255, 255));
        People_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        People_Label.setText("How many People are you?");
        kGradientPanel2.add(People_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 100));

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 410, 100));

        No_of_People_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_of_People_FieldActionPerformed(evt);
            }
        });
        No_of_People_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                No_of_People_FieldKeyReleased(evt);
            }
        });
        kGradientPanel1.add(No_of_People_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 310, 50));

        Next_Button.setText("Next");
        Next_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Next_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_ButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Next_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 130, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Next_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_ButtonActionPerformed
        // TODO add your handling code here:
        String Number_of_People = No_of_People_Field.getText();
        int number = Integer.parseInt(Number_of_People);
        
        if(Number_of_People.matches("^[1-9]*$"))
        {
            Customer_Tables tables = new Customer_Tables();
            tables.setVisible(true);
            tables.Table_Selection_Function(number);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Invalid Number");
        }
        
        
    }//GEN-LAST:event_Next_ButtonActionPerformed

    private void No_of_People_FieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_No_of_People_FieldKeyReleased
        // TODO add your handling code here:     \
        String Number_of_People = No_of_People_Field.getText();
        
        if(Number_of_People.matches("^[1-9]*$"))
        {
            No_of_People_Field.setBackground(Color.green);
        }
        else
        {
            No_of_People_Field.setBackground(Color.red);
        }
        
    }//GEN-LAST:event_No_of_People_FieldKeyReleased

    private void No_of_People_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_of_People_FieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_No_of_People_FieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dine_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dine_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dine_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dine_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dine_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton Next_Button;
    private javax.swing.JTextField No_of_People_Field;
    private javax.swing.JLabel People_Label;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
