/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhammad Waseem
 */
public class FAST_FOOD extends javax.swing.JFrame {

    private int Total_Amount = 0;
    /**
     * Creates new form FAST_FOOD
     */
    public FAST_FOOD() {
        initComponents();
    }
    
    public void Total_Fast_Food(int amount)
    {
        this.Total_Amount += amount;
    }
    

        public void Import_File()
    {
        String Filepath = "E:\\Rice.txt";
        File file = new File(Filepath);
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i=0;i<lines.length;i++)
            {
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Table2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void Export_File()
    {
        String Filepath = "E:\\Rice.txt";
        File file = new File(Filepath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i=0;i<jTable1.getRowCount();i++)
            {
                for(int j=0;j<jTable1.getColumnCount();j++)
                {
                    bw.write(jTable1.getValueAt(i, j).toString()+" ");
                }
                bw.newLine();
            }
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Table.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void Fast_Food(String name, int price) 
    {
        int Quantity = Integer.parseInt(JOptionPane.showInputDialog(null, "Quantity"));
        if (Quantity > 0) 
        {
            int Total = price * Quantity;
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]
            {
                name,
                price,
                Quantity,
                Total

            });
                    this.Total_Amount += Total;
        }

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ALL_BUTTON = new javax.swing.JButton();
        BAR_B_Q_BUTTON1 = new javax.swing.JButton();
        KARAHI_BUTTON = new javax.swing.JButton();
        RICE_BUTTON = new javax.swing.JButton();
        VEGETABLES_BUTTON = new javax.swing.JButton();
        BEANS_BUTTON = new javax.swing.JButton();
        CHINES_DISHES_BUTTON = new javax.swing.JButton();
        FAST_FOOD_BUTTON = new javax.swing.JButton();
        SWEETS_BUTTON = new javax.swing.JButton();
        COLD_DRINKS_BUTTON = new javax.swing.JButton();
        TUNDOOR_BUTTON = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        Cash_Remained = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Total_TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Cash_Recieved = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Delete_Row = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        Fajita_Pannel = new javax.swing.JPanel();
        Fajita_Label = new javax.swing.JLabel();
        Fajita_Price = new javax.swing.JLabel();
        Tikka_Pannel = new javax.swing.JPanel();
        Tikka_Label = new javax.swing.JLabel();
        Tikka_Price = new javax.swing.JLabel();
        Creamy_Melt_Pannel = new javax.swing.JPanel();
        Creamy_Melt_Label = new javax.swing.JLabel();
        Creamy_Melt_Price = new javax.swing.JLabel();
        Hawaiian_Pannel = new javax.swing.JPanel();
        Hawaiian_Label = new javax.swing.JLabel();
        Hawaiian_Price = new javax.swing.JLabel();
        Cheese_Lover_Pannel = new javax.swing.JPanel();
        Cheese_Lover_Label = new javax.swing.JLabel();
        Cheese_Lover_Price = new javax.swing.JLabel();
        Behari_Kabab_Pannel = new javax.swing.JPanel();
        Behari_Kabab_Label = new javax.swing.JLabel();
        Behari_Kabab_Price = new javax.swing.JLabel();
        BBQ_Pannel = new javax.swing.JPanel();
        BBQ_Label = new javax.swing.JLabel();
        BBQ_Price = new javax.swing.JLabel();
        Train_Pizza_Pannel = new javax.swing.JPanel();
        Train_Pizza_Label = new javax.swing.JLabel();
        Train_Pizza_Price = new javax.swing.JLabel();
        Ande_wala_Burger_Pannel = new javax.swing.JPanel();
        Ande_wala_Burger_Label = new javax.swing.JLabel();
        Ande_wala_Burger_Price1 = new javax.swing.JLabel();
        Zinger_Burger_Pannel = new javax.swing.JPanel();
        Zinger_Burger_Label = new javax.swing.JLabel();
        Zinger_Burger_Price = new javax.swing.JLabel();
        Tower_Burger_Pannel = new javax.swing.JPanel();
        Tower_Burger_Label = new javax.swing.JLabel();
        Tower_Burger_Price = new javax.swing.JLabel();
        Chicken_Shawarma_Pannel = new javax.swing.JPanel();
        Chicken_Shawarma_Label = new javax.swing.JLabel();
        Chicken_Shawarma_Price = new javax.swing.JLabel();
        Zinger_Shawarma_Pannel = new javax.swing.JPanel();
        Zinger_Shawarma_Label = new javax.swing.JLabel();
        Zinger_Shawarma_Price = new javax.swing.JLabel();
        Nuggets_Pannel = new javax.swing.JPanel();
        Nuggets_Label = new javax.swing.JLabel();
        Nuggets_Price = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ALL_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        ALL_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ALL_BUTTON.setText("ALL PRODUCTS");
        ALL_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALL_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(ALL_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        BAR_B_Q_BUTTON1.setBackground(new java.awt.Color(51, 255, 51));
        BAR_B_Q_BUTTON1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BAR_B_Q_BUTTON1.setText("BAR-B-Q");
        BAR_B_Q_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAR_B_Q_BUTTON1ActionPerformed(evt);
            }
        });
        jPanel2.add(BAR_B_Q_BUTTON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 50));

        KARAHI_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        KARAHI_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        KARAHI_BUTTON.setText("KARAHI");
        KARAHI_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KARAHI_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(KARAHI_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 50));

        RICE_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        RICE_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RICE_BUTTON.setText("RICE");
        RICE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RICE_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(RICE_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 50));

        VEGETABLES_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        VEGETABLES_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        VEGETABLES_BUTTON.setText("VEGETABLES");
        VEGETABLES_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VEGETABLES_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(VEGETABLES_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 50));

        BEANS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        BEANS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BEANS_BUTTON.setText("BEANS");
        BEANS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEANS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(BEANS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 150, 50));

        CHINES_DISHES_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        CHINES_DISHES_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CHINES_DISHES_BUTTON.setText("CHINESE DISHES");
        CHINES_DISHES_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHINES_DISHES_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(CHINES_DISHES_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 150, 50));

        FAST_FOOD_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        FAST_FOOD_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        FAST_FOOD_BUTTON.setText("FAST FOOD");
        FAST_FOOD_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAST_FOOD_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(FAST_FOOD_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 150, 50));

        SWEETS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        SWEETS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SWEETS_BUTTON.setText("DESSERTS");
        SWEETS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SWEETS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(SWEETS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 150, 50));

        COLD_DRINKS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        COLD_DRINKS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        COLD_DRINKS_BUTTON.setText("BEVERAGES");
        COLD_DRINKS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COLD_DRINKS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(COLD_DRINKS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 150, 50));

        TUNDOOR_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        TUNDOOR_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TUNDOOR_BUTTON.setText("FROM TUNDOOR");
        TUNDOOR_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUNDOOR_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(TUNDOOR_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 150, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel3.setBackground(new java.awt.Color(102, 255, 204));
        jPanel3.setLayout(null);

        Cash_Remained.setBackground(new java.awt.Color(153, 255, 153));
        Cash_Remained.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cash_Remained.setForeground(new java.awt.Color(204, 0, 0));
        jPanel3.add(Cash_Remained);
        Cash_Remained.setBounds(190, 130, 154, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Rs.");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(350, 90, 33, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Return");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 130, 170, 30);

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Ready for Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(0, 0, 190, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total Price");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 50, 170, 30);

        Total_TextField.setBackground(new java.awt.Color(153, 255, 153));
        Total_TextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Total_TextField.setForeground(new java.awt.Color(204, 0, 0));
        Total_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_TextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(Total_TextField);
        Total_TextField.setBounds(190, 50, 154, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Rs.");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(350, 130, 33, 32);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cash Recieved");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 90, 170, 30);

        Cash_Recieved.setBackground(new java.awt.Color(153, 255, 153));
        Cash_Recieved.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cash_Recieved.setForeground(new java.awt.Color(204, 0, 0));
        Cash_Recieved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cash_RecievedActionPerformed(evt);
            }
        });
        Cash_Recieved.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Cash_RecievedKeyPressed(evt);
            }
        });
        jPanel3.add(Cash_Recieved);
        Cash_Recieved.setBounds(190, 90, 154, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Rs.");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(350, 50, 33, 30);

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Print Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(190, 170, 150, 50);

        Delete_Row.setBackground(new java.awt.Color(153, 255, 153));
        Delete_Row.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Delete_Row.setForeground(new java.awt.Color(204, 0, 0));
        Delete_Row.setText("Delete Some Item/Row");
        Delete_Row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_RowActionPerformed(evt);
            }
        });
        jPanel3.add(Delete_Row);
        Delete_Row.setBounds(270, 0, 190, 40);

        Fajita_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Fajita_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Fajita_PannelMouseClicked(evt);
            }
        });
        Fajita_Pannel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Fajita_PannelKeyPressed(evt);
            }
        });
        Fajita_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fajita_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Fajita_Label.setForeground(new java.awt.Color(204, 0, 0));
        Fajita_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fajita_Label.setText("Pizza_Fajita");
        Fajita_Pannel.add(Fajita_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, -1));

        Fajita_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Fajita_Price.setForeground(new java.awt.Color(204, 0, 0));
        Fajita_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fajita_Price.setText("Price = Different.");
        Fajita_Pannel.add(Fajita_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, -1));

        Tikka_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Tikka_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tikka_PannelMouseClicked(evt);
            }
        });
        Tikka_Pannel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tikka_PannelKeyPressed(evt);
            }
        });
        Tikka_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tikka_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Tikka_Label.setForeground(new java.awt.Color(204, 0, 0));
        Tikka_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tikka_Label.setText("Pizza_Tikka");
        Tikka_Pannel.add(Tikka_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        Tikka_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Tikka_Price.setForeground(new java.awt.Color(204, 0, 0));
        Tikka_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tikka_Price.setText("Price = Different");
        Tikka_Pannel.add(Tikka_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        Creamy_Melt_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Creamy_Melt_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Creamy_Melt_PannelMouseClicked(evt);
            }
        });
        Creamy_Melt_Pannel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Creamy_Melt_PannelKeyPressed(evt);
            }
        });
        Creamy_Melt_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Creamy_Melt_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Creamy_Melt_Label.setForeground(new java.awt.Color(204, 0, 0));
        Creamy_Melt_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Creamy_Melt_Label.setText("Creamy_Melt");
        Creamy_Melt_Pannel.add(Creamy_Melt_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, 100, -1));

        Creamy_Melt_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Creamy_Melt_Price.setForeground(new java.awt.Color(204, 0, 0));
        Creamy_Melt_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Creamy_Melt_Price.setText("Price = Different.");
        Creamy_Melt_Pannel.add(Creamy_Melt_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 30, 100, -1));

        Hawaiian_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Hawaiian_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Hawaiian_PannelMouseClicked(evt);
            }
        });
        Hawaiian_Pannel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Hawaiian_PannelKeyPressed(evt);
            }
        });
        Hawaiian_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hawaiian_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Hawaiian_Label.setForeground(new java.awt.Color(204, 0, 0));
        Hawaiian_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hawaiian_Label.setText("Pizza_Hawaiian");
        Hawaiian_Pannel.add(Hawaiian_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        Hawaiian_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Hawaiian_Price.setForeground(new java.awt.Color(204, 0, 0));
        Hawaiian_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hawaiian_Price.setText("Price = Different");
        Hawaiian_Pannel.add(Hawaiian_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, -1));

        Cheese_Lover_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Cheese_Lover_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cheese_Lover_PannelMouseClicked(evt);
            }
        });
        Cheese_Lover_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cheese_Lover_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Cheese_Lover_Label.setForeground(new java.awt.Color(204, 0, 0));
        Cheese_Lover_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cheese_Lover_Label.setText("Pizza_CheeseLover");
        Cheese_Lover_Pannel.add(Cheese_Lover_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 10, 120, -1));

        Cheese_Lover_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Cheese_Lover_Price.setForeground(new java.awt.Color(204, 0, 0));
        Cheese_Lover_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cheese_Lover_Price.setText("Price = Different");
        Cheese_Lover_Pannel.add(Cheese_Lover_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, -1));

        Behari_Kabab_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Behari_Kabab_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Behari_Kabab_PannelMouseClicked(evt);
            }
        });
        Behari_Kabab_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Behari_Kabab_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Behari_Kabab_Label.setForeground(new java.awt.Color(204, 0, 0));
        Behari_Kabab_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Behari_Kabab_Label.setText("Behari_Kabab");
        Behari_Kabab_Pannel.add(Behari_Kabab_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 74, -1));

        Behari_Kabab_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Behari_Kabab_Price.setForeground(new java.awt.Color(204, 0, 0));
        Behari_Kabab_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Behari_Kabab_Price.setText("Price = Different");
        Behari_Kabab_Pannel.add(Behari_Kabab_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 30, 130, -1));

        BBQ_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        BBQ_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BBQ_PannelMouseClicked(evt);
            }
        });
        BBQ_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BBQ_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        BBQ_Label.setForeground(new java.awt.Color(204, 0, 0));
        BBQ_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BBQ_Label.setText("Pizza_BBQ");
        BBQ_Pannel.add(BBQ_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 10, 120, -1));

        BBQ_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        BBQ_Price.setForeground(new java.awt.Color(204, 0, 0));
        BBQ_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BBQ_Price.setText("Price = Different");
        BBQ_Pannel.add(BBQ_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, -1));

        Train_Pizza_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Train_Pizza_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Train_Pizza_PannelMouseClicked(evt);
            }
        });
        Train_Pizza_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Train_Pizza_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Train_Pizza_Label.setForeground(new java.awt.Color(204, 0, 0));
        Train_Pizza_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Train_Pizza_Label.setText("Train_Pizza");
        Train_Pizza_Pannel.add(Train_Pizza_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 74, -1));

        Train_Pizza_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Train_Pizza_Price.setForeground(new java.awt.Color(204, 0, 0));
        Train_Pizza_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Train_Pizza_Price.setText("Price = 2000Rs.");
        Train_Pizza_Pannel.add(Train_Pizza_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, -1));

        Ande_wala_Burger_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Ande_wala_Burger_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ande_wala_Burger_PannelMouseClicked(evt);
            }
        });
        Ande_wala_Burger_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ande_wala_Burger_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Ande_wala_Burger_Label.setForeground(new java.awt.Color(204, 0, 0));
        Ande_wala_Burger_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ande_wala_Burger_Label.setText("Ande_Wala_Burger");
        Ande_wala_Burger_Pannel.add(Ande_wala_Burger_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, -1));

        Ande_wala_Burger_Price1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Ande_wala_Burger_Price1.setForeground(new java.awt.Color(204, 0, 0));
        Ande_wala_Burger_Price1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ande_wala_Burger_Price1.setText("Price = 50Rs.");
        Ande_wala_Burger_Pannel.add(Ande_wala_Burger_Price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 75, -1));

        Zinger_Burger_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Zinger_Burger_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Zinger_Burger_PannelMouseClicked(evt);
            }
        });
        Zinger_Burger_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Zinger_Burger_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Zinger_Burger_Label.setForeground(new java.awt.Color(204, 0, 0));
        Zinger_Burger_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Zinger_Burger_Label.setText("Zinger_Burger");
        Zinger_Burger_Pannel.add(Zinger_Burger_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        Zinger_Burger_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Zinger_Burger_Price.setForeground(new java.awt.Color(204, 0, 0));
        Zinger_Burger_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Zinger_Burger_Price.setText("Price = 120Rs.");
        Zinger_Burger_Pannel.add(Zinger_Burger_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        Tower_Burger_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Tower_Burger_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tower_Burger_PannelMouseClicked(evt);
            }
        });
        Tower_Burger_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tower_Burger_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Tower_Burger_Label.setForeground(new java.awt.Color(204, 0, 0));
        Tower_Burger_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tower_Burger_Label.setText("Tower_Burger");
        Tower_Burger_Pannel.add(Tower_Burger_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 130, -1));

        Tower_Burger_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Tower_Burger_Price.setForeground(new java.awt.Color(204, 0, 0));
        Tower_Burger_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tower_Burger_Price.setText("Price = 180Rs.");
        Tower_Burger_Pannel.add(Tower_Burger_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, -1));

        Chicken_Shawarma_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Chicken_Shawarma_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chicken_Shawarma_PannelMouseClicked(evt);
            }
        });
        Chicken_Shawarma_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Chicken_Shawarma_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chicken_Shawarma_Label.setForeground(new java.awt.Color(204, 0, 0));
        Chicken_Shawarma_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken_Shawarma_Label.setText("Chicken_Shawarma");
        Chicken_Shawarma_Pannel.add(Chicken_Shawarma_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 10, 110, -1));

        Chicken_Shawarma_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chicken_Shawarma_Price.setForeground(new java.awt.Color(204, 0, 0));
        Chicken_Shawarma_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken_Shawarma_Price.setText("Price = 60Rs.");
        Chicken_Shawarma_Pannel.add(Chicken_Shawarma_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, -1));

        Zinger_Shawarma_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Zinger_Shawarma_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Zinger_Shawarma_PannelMouseClicked(evt);
            }
        });
        Zinger_Shawarma_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Zinger_Shawarma_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Zinger_Shawarma_Label.setForeground(new java.awt.Color(204, 0, 0));
        Zinger_Shawarma_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Zinger_Shawarma_Label.setText("Zinger_Shawarma");
        Zinger_Shawarma_Pannel.add(Zinger_Shawarma_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 110, -1));

        Zinger_Shawarma_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Zinger_Shawarma_Price.setForeground(new java.awt.Color(204, 0, 0));
        Zinger_Shawarma_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Zinger_Shawarma_Price.setText("Price = 80Rs.");
        Zinger_Shawarma_Pannel.add(Zinger_Shawarma_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        Nuggets_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Nuggets_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Nuggets_PannelMouseClicked(evt);
            }
        });
        Nuggets_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nuggets_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Nuggets_Label.setForeground(new java.awt.Color(204, 0, 0));
        Nuggets_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nuggets_Label.setText("Nuggets");
        Nuggets_Pannel.add(Nuggets_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 10, 120, -1));

        Nuggets_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Nuggets_Price.setForeground(new java.awt.Color(204, 0, 0));
        Nuggets_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nuggets_Price.setText("Price = 20Rs./Per piece");
        Nuggets_Pannel.add(Nuggets_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Pizzas/Chicken Fajita.jpg"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Pizzas/Chicken Tikka.jpg"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Pizzas/Creamy Melt.jpg"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Pizzas/Hawaiian.jpg"))); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Pizzas/Train Pizza.jpg"))); // NOI18N

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Pizzas/BBQ Chicken.jpg"))); // NOI18N

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Pizzas/Behari Kabab.jpg"))); // NOI18N

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Pizzas/Cheese Lover.jpg"))); // NOI18N

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Pizzas/Ande Wala Burger.jpg"))); // NOI18N

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Pizzas/Zinger Burger.jpg"))); // NOI18N

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Pizzas/Tower Burger.jpg"))); // NOI18N

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Pizzas/Chicken Shawarma.jpg"))); // NOI18N

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Pizzas/Nuggets.jpg"))); // NOI18N

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Pizzas/Zinger Shawarma.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(Fajita_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Tikka_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Creamy_Melt_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Hawaiian_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel10))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(Nuggets_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(Zinger_Shawarma_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(Ande_wala_Burger_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Zinger_Burger_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Tower_Burger_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Chicken_Shawarma_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(Cheese_Lover_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Behari_Kabab_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(BBQ_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Train_Pizza_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel11)
                                    .addGap(198, 198, 198)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(188, 188, 188)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fajita_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tikka_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Creamy_Melt_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hawaiian_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(304, 304, 304))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cheese_Lover_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BBQ_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Train_Pizza_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Behari_Kabab_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Zinger_Burger_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ande_wala_Burger_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tower_Burger_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Chicken_Shawarma_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(Nuggets_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel15))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Zinger_Shawarma_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
        );

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ALL_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALL_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        All_Products all = new All_Products();
        all.Total_Products(this.Total_Amount);
        all.setVisible(true);
        this.dispose();
        all.Import_File();
    }//GEN-LAST:event_ALL_BUTTONActionPerformed

    private void BAR_B_Q_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAR_B_Q_BUTTON1ActionPerformed
        // TODO add your handling code here:
        Export_File();
        BAR_B_Q_Page b = new BAR_B_Q_Page();
        b.Total_BBQ(this.Total_Amount);
        b.setVisible(true);
        this.dispose();
        b.Import_File();
    }//GEN-LAST:event_BAR_B_Q_BUTTON1ActionPerformed

    private void KARAHI_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KARAHI_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        KARAHI K =new KARAHI();
        K.Total_Karahi(this.Total_Amount);
        K.setVisible(true);
        this.dispose();
        K.Import_File();
    }//GEN-LAST:event_KARAHI_BUTTONActionPerformed

    private void RICE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RICE_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        RICE rice = new RICE();
        rice.Total_Rice(this.Total_Amount);
        rice.setVisible(true);
        this.dispose();
        rice.Import_File();
    }//GEN-LAST:event_RICE_BUTTONActionPerformed

    private void VEGETABLES_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VEGETABLES_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        VEGETABLES vege = new VEGETABLES();
        vege.Total_Vegetables(this.Total_Amount);
        vege.setVisible(true);
        this.dispose();
        vege.Import_File();
    }//GEN-LAST:event_VEGETABLES_BUTTONActionPerformed

    private void BEANS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEANS_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        BEANS beans = new BEANS();
        beans.Total_Beans(this.Total_Amount);
        beans.setVisible(true);
        this.dispose();
        beans.Import_File();
    }//GEN-LAST:event_BEANS_BUTTONActionPerformed

    private void CHINES_DISHES_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHINES_DISHES_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        CHINESE_DISHES china = new CHINESE_DISHES();
        china.Total_Chinese_Dishes(this.Total_Amount);
        china.setVisible(true);
        this.dispose();
        china.Import_File();
    }//GEN-LAST:event_CHINES_DISHES_BUTTONActionPerformed

    private void FAST_FOOD_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAST_FOOD_BUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FAST_FOOD_BUTTONActionPerformed

    private void SWEETS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SWEETS_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        DESSERTS dessert =  new DESSERTS();
        dessert.Total_Desserts(this.Total_Amount);
        dessert.setVisible(true);
        this.dispose();
        dessert.Import_File();
    }//GEN-LAST:event_SWEETS_BUTTONActionPerformed

    private void COLD_DRINKS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COLD_DRINKS_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        BEVERAGES drinks = new BEVERAGES();
        drinks.Total_Drinks(this.Total_Amount);
        drinks.setVisible(true);
        this.dispose();
        drinks.Import_File();
    }//GEN-LAST:event_COLD_DRINKS_BUTTONActionPerformed

    private void TUNDOOR_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUNDOOR_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        TUNDOOR roti = new TUNDOOR();
        roti.Total_Tundoor(this.Total_Amount);
        roti.setVisible(true);
        this.dispose();
        roti.Import_File();
    }//GEN-LAST:event_TUNDOOR_BUTTONActionPerformed

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Delete_Row.setEnabled(false);
        Total_TextField.setText("");
        Cash_Recieved.setText("");
        Cash_Remained.setText("");

        String Total = Integer.toString(this.Total_Amount);
        Total_TextField.setText(Total);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Total_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_TextFieldActionPerformed

    private void Cash_RecievedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cash_RecievedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cash_RecievedActionPerformed

    private void Cash_RecievedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cash_RecievedKeyPressed
        // TODO add your handling code here:

        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {

            String Cash = Cash_Recieved.getText();
            int Cash_Int = Integer.parseInt(Cash);
            int Remaining_Int = Cash_Int - this.Total_Amount;
            if (Remaining_Int > 0) 
            {
                String Remaining = Integer.toString(Remaining_Int);
                Cash_Remained.setText(Remaining);
            }

        }
    }//GEN-LAST:event_Cash_RecievedKeyPressed

    private void Delete_RowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_RowActionPerformed
        // TODO add your handling code here:
        Total_TextField.setText("");
        Cash_Recieved.setText("");
        Cash_Remained.setText("");
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int i = jTable1.getSelectedRow();
        
        
        String Filepath = "E:\\Restaurant-Managememt-System-Java\\Row_Price.txt";
        File file = new File(Filepath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            bw.write(jTable1.getValueAt(i, 3).toString());
            
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Table.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        if(jTable1.getSelectedRow()>=0)
        {
            model.removeRow(jTable1.getSelectedRow());      
        }
        else
        {
            JOptionPane.showMessageDialog(null, "First Select the Row!");
        }
        
       try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);

            Object[] lines = br.lines().toArray();
            String row ="";
            for(int k =0 ; k<lines.length; k++)
            {
                row += lines[k];
            }
            int row_int = 0;
            row_int = Integer.parseInt(row);
            this.Total_Amount -= row_int;
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(KARAHI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Delete_RowActionPerformed

    private void Fajita_PannelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Fajita_PannelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fajita_PannelKeyPressed

    private void Tikka_PannelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tikka_PannelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tikka_PannelKeyPressed

    private void Creamy_Melt_PannelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Creamy_Melt_PannelKeyPressed
        // TODO add your handling code here
    }//GEN-LAST:event_Creamy_Melt_PannelKeyPressed

    private void Creamy_Melt_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Creamy_Melt_PannelMouseClicked
        // TODO add your handling code here:
        String name = Creamy_Melt_Label.getText();
        String Size_Dish[] =  {"Small","Medium","Large"};
        JComboBox cb = new JComboBox(Size_Dish);
        int Input = JOptionPane.showConfirmDialog(rootPane, cb,"Select Size",JOptionPane.DEFAULT_OPTION);
        if(Input == JOptionPane.OK_OPTION)
        {
            String size = (String)cb.getSelectedItem();
            
            if(size == "Small")
            {
                int price = 500;
                Fast_Food(name,price);
            }
            else if(size == "Medium")
            {
                int price = 700;
                Fast_Food(name,price);
            }
            else
            {
                int price = 1100;
                Fast_Food(name,price);
            }
        }
    }//GEN-LAST:event_Creamy_Melt_PannelMouseClicked

    private void Tikka_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tikka_PannelMouseClicked
        // TODO add your handling code here:
        String name = Tikka_Label.getText();
        String Size_Dish[] =  {"Small","Medium","Large"};
        JComboBox cb = new JComboBox(Size_Dish);
        int Input = JOptionPane.showConfirmDialog(rootPane, cb,"Select Size",JOptionPane.DEFAULT_OPTION);
        if(Input == JOptionPane.OK_OPTION)
        {
            String size = (String)cb.getSelectedItem();
            
            if(size == "Small")
            {
                int price = 500;
                Fast_Food(name,price);
            }
            else if(size == "Medium")
            {
                int price = 700;
                Fast_Food(name,price);
            }
            else
            {
                int price = 1100;
                Fast_Food(name,price);
            }
        }
    }//GEN-LAST:event_Tikka_PannelMouseClicked

    private void Fajita_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fajita_PannelMouseClicked
        // TODO add your handling code here:
        String name = Fajita_Label.getText();
        String Size_Dish[] =  {"Small","Medium","Large"};
        JComboBox cb = new JComboBox(Size_Dish);
        int Input = JOptionPane.showConfirmDialog(rootPane, cb,"Select Size",JOptionPane.DEFAULT_OPTION);
        if(Input == JOptionPane.OK_OPTION)
        {
            String size = (String)cb.getSelectedItem();
            
            if(size == "Small")
            {
                int price = 500;
                Fast_Food(name,price);
            }
            else if(size == "Medium")
            {
                int price = 700;
                Fast_Food(name,price);
            }
            else
            {
                int price = 1100;
                Fast_Food(name,price);
            }
        }
    }//GEN-LAST:event_Fajita_PannelMouseClicked

    private void Hawaiian_PannelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Hawaiian_PannelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hawaiian_PannelKeyPressed

    private void Hawaiian_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hawaiian_PannelMouseClicked
        // TODO add your handling code here:
        String name = Hawaiian_Label.getText();
        String Size_Dish[] =  {"Small","Medium","Large"};
        JComboBox cb = new JComboBox(Size_Dish);
        int Input = JOptionPane.showConfirmDialog(rootPane, cb,"Select Size",JOptionPane.DEFAULT_OPTION);
        if(Input == JOptionPane.OK_OPTION)
        {
            String size = (String)cb.getSelectedItem();
            
            if(size == "Small")
            {
                int price = 500;
                Fast_Food(name,price);
            }
            else if(size == "Medium")
            {
                int price = 700;
                Fast_Food(name,price);
            }
            else
            {
                int price = 1100;
                Fast_Food(name,price);
            }
        }
    }//GEN-LAST:event_Hawaiian_PannelMouseClicked

    private void Cheese_Lover_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cheese_Lover_PannelMouseClicked
        // TODO add your handling code here:
        String name = Cheese_Lover_Label.getText();
        String Size_Dish[] =  {"Small","Medium","Large"};
        JComboBox cb = new JComboBox(Size_Dish);
        int Input = JOptionPane.showConfirmDialog(rootPane, cb,"Select Size",JOptionPane.DEFAULT_OPTION);
        if(Input == JOptionPane.OK_OPTION)
        {
            String size = (String)cb.getSelectedItem();
            
            if(size == "Small")
            {
                int price = 500;
                Fast_Food(name,price);
            }
            else if(size == "Medium")
            {
                int price = 700;
                Fast_Food(name,price);
            }
            else
            {
                int price = 1100;
                Fast_Food(name,price);
            }
        }
    }//GEN-LAST:event_Cheese_Lover_PannelMouseClicked

    private void Behari_Kabab_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Behari_Kabab_PannelMouseClicked
        // TODO add your handling code here:
        String name = Behari_Kabab_Label.getText();
        String Size_Dish[] =  {"Small","Medium","Large"};
        JComboBox cb = new JComboBox(Size_Dish);
        int Input = JOptionPane.showConfirmDialog(rootPane, cb,"Select Size",JOptionPane.DEFAULT_OPTION);
        if(Input == JOptionPane.OK_OPTION)
        {
            String size = (String)cb.getSelectedItem();
            
            if(size == "Small")
            {
                int price = 500;
                Fast_Food(name,price);
            }
            else if(size == "Medium")
            {
                int price = 700;
                Fast_Food(name,price);
            }
            else
            {
                int price = 1100;
                Fast_Food(name,price);
            }
        }
    }//GEN-LAST:event_Behari_Kabab_PannelMouseClicked

    private void BBQ_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BBQ_PannelMouseClicked
        // TODO add your handling code here:
        String name = BBQ_Label.getText();
        String Size_Dish[] =  {"Small","Medium","Large"};
        JComboBox cb = new JComboBox(Size_Dish);
        int Input = JOptionPane.showConfirmDialog(rootPane, cb,"Select Size",JOptionPane.DEFAULT_OPTION);
        if(Input == JOptionPane.OK_OPTION)
        {
            String size = (String)cb.getSelectedItem();
            
            if(size == "Small")
            {
                int price = 500;
                Fast_Food(name,price);
            }
            else if(size == "Medium")
            {
                int price = 700;
                Fast_Food(name,price);
            }
            else
            {
                int price = 1100;
                Fast_Food(name,price);
            }
        }
    }//GEN-LAST:event_BBQ_PannelMouseClicked

    private void Train_Pizza_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Train_Pizza_PannelMouseClicked
        // TODO add your handling code here:
        String name = Train_Pizza_Label.getText();
        int price = 2000;
        Fast_Food(name,price);
    }//GEN-LAST:event_Train_Pizza_PannelMouseClicked

    private void Ande_wala_Burger_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ande_wala_Burger_PannelMouseClicked
        // TODO add your handling code here:
        String name = Ande_wala_Burger_Label.getText();        
        int price = 50;
        Fast_Food(name,price);
    }//GEN-LAST:event_Ande_wala_Burger_PannelMouseClicked

    private void Zinger_Burger_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Zinger_Burger_PannelMouseClicked
        // TODO add your handling code here:
        String name = Zinger_Burger_Label.getText();
        int price = 120;
        Fast_Food(name,price);
    }//GEN-LAST:event_Zinger_Burger_PannelMouseClicked

    private void Tower_Burger_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tower_Burger_PannelMouseClicked
        // TODO add your handling code here:
        String name = Tower_Burger_Label.getText();
        int price = 180;
        Fast_Food(name,price);
    }//GEN-LAST:event_Tower_Burger_PannelMouseClicked

    private void Chicken_Shawarma_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chicken_Shawarma_PannelMouseClicked
        // TODO add your handling code here:
        String name = Chicken_Shawarma_Label.getText();
        int price = 60;
        Fast_Food(name,price);
    }//GEN-LAST:event_Chicken_Shawarma_PannelMouseClicked

    private void Zinger_Shawarma_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Zinger_Shawarma_PannelMouseClicked
        // TODO add your handling code here:
        String name = Zinger_Shawarma_Label.getText();
        int price = 80;
        Fast_Food(name,price);
    }//GEN-LAST:event_Zinger_Shawarma_PannelMouseClicked

    private void Nuggets_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nuggets_PannelMouseClicked
        // TODO add your handling code here:
        String name = Nuggets_Label.getText();
        int price = 20;
        Fast_Food(name,price);
    }//GEN-LAST:event_Nuggets_PannelMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Export_File();
        Bill bill = new Bill();
        bill.Total_Bill(this.Total_Amount,Cash_Recieved.getText(),Cash_Remained.getText());
        bill.setVisible(true);
        bill.Import_File();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAST_FOOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAST_FOOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAST_FOOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAST_FOOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAST_FOOD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ALL_BUTTON;
    private javax.swing.JLabel Ande_wala_Burger_Label;
    private javax.swing.JPanel Ande_wala_Burger_Pannel;
    private javax.swing.JLabel Ande_wala_Burger_Price1;
    private javax.swing.JButton BAR_B_Q_BUTTON1;
    private javax.swing.JLabel BBQ_Label;
    private javax.swing.JPanel BBQ_Pannel;
    private javax.swing.JLabel BBQ_Price;
    private javax.swing.JButton BEANS_BUTTON;
    private javax.swing.JLabel Behari_Kabab_Label;
    private javax.swing.JPanel Behari_Kabab_Pannel;
    private javax.swing.JLabel Behari_Kabab_Price;
    private javax.swing.JButton CHINES_DISHES_BUTTON;
    private javax.swing.JButton COLD_DRINKS_BUTTON;
    private javax.swing.JTextField Cash_Recieved;
    private javax.swing.JTextField Cash_Remained;
    private javax.swing.JLabel Cheese_Lover_Label;
    private javax.swing.JPanel Cheese_Lover_Pannel;
    private javax.swing.JLabel Cheese_Lover_Price;
    private javax.swing.JLabel Chicken_Shawarma_Label;
    private javax.swing.JPanel Chicken_Shawarma_Pannel;
    private javax.swing.JLabel Chicken_Shawarma_Price;
    private javax.swing.JLabel Creamy_Melt_Label;
    private javax.swing.JPanel Creamy_Melt_Pannel;
    private javax.swing.JLabel Creamy_Melt_Price;
    private javax.swing.JButton Delete_Row;
    private javax.swing.JButton FAST_FOOD_BUTTON;
    private javax.swing.JLabel Fajita_Label;
    private javax.swing.JPanel Fajita_Pannel;
    private javax.swing.JLabel Fajita_Price;
    private javax.swing.JLabel Hawaiian_Label;
    private javax.swing.JPanel Hawaiian_Pannel;
    private javax.swing.JLabel Hawaiian_Price;
    private javax.swing.JButton KARAHI_BUTTON;
    private javax.swing.JLabel Nuggets_Label;
    private javax.swing.JPanel Nuggets_Pannel;
    private javax.swing.JLabel Nuggets_Price;
    private javax.swing.JButton RICE_BUTTON;
    private javax.swing.JButton SWEETS_BUTTON;
    private javax.swing.JButton TUNDOOR_BUTTON;
    private javax.swing.JLabel Tikka_Label;
    private javax.swing.JPanel Tikka_Pannel;
    private javax.swing.JLabel Tikka_Price;
    private javax.swing.JTextField Total_TextField;
    private javax.swing.JLabel Tower_Burger_Label;
    private javax.swing.JPanel Tower_Burger_Pannel;
    private javax.swing.JLabel Tower_Burger_Price;
    private javax.swing.JLabel Train_Pizza_Label;
    private javax.swing.JPanel Train_Pizza_Pannel;
    private javax.swing.JLabel Train_Pizza_Price;
    private javax.swing.JButton VEGETABLES_BUTTON;
    private javax.swing.JLabel Zinger_Burger_Label;
    private javax.swing.JPanel Zinger_Burger_Pannel;
    private javax.swing.JLabel Zinger_Burger_Price;
    private javax.swing.JLabel Zinger_Shawarma_Label;
    private javax.swing.JPanel Zinger_Shawarma_Pannel;
    private javax.swing.JLabel Zinger_Shawarma_Price;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
