/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import javax.swing.JFrame;

/**
 *
 * @author Muhammad Waseem
 */
public class FrontPage extends javax.swing.JFrame {

    /**
     * Creates new form FrontPage
     */
    public FrontPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginButton = new keeptoo.KButton();
        SignupButton = new keeptoo.KButton();
        RESButton = new keeptoo.KButton();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginButton.setBorder(null);
        LoginButton.setText("Login");
        LoginButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LoginButton.setkBorderRadius(40);
        LoginButton.setkEndColor(new java.awt.Color(255, 255, 0));
        LoginButton.setkHoverEndColor(new java.awt.Color(153, 153, 0));
        LoginButton.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        LoginButton.setkHoverStartColor(new java.awt.Color(255, 51, 0));
        LoginButton.setkStartColor(new java.awt.Color(255, 102, 51));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 70, 30));

        SignupButton.setBorder(null);
        SignupButton.setText("Sign up");
        SignupButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        SignupButton.setkBorderRadius(40);
        SignupButton.setkEndColor(new java.awt.Color(255, 255, 0));
        SignupButton.setkHoverEndColor(new java.awt.Color(153, 153, 0));
        SignupButton.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        SignupButton.setkHoverStartColor(new java.awt.Color(255, 51, 0));
        SignupButton.setkStartColor(new java.awt.Color(255, 102, 51));
        SignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SignupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 70, 30));

        RESButton.setBorder(null);
        RESButton.setText("Restaurant Management System");
        RESButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RESButton.setkBorderRadius(30);
        RESButton.setkEndColor(new java.awt.Color(255, 255, 0));
        RESButton.setkHoverEndColor(new java.awt.Color(153, 153, 0));
        RESButton.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        RESButton.setkHoverStartColor(new java.awt.Color(255, 51, 0));
        RESButton.setkStartColor(new java.awt.Color(255, 102, 51));
        RESButton.setMargin(new java.awt.Insets(1, 14, 2, 14));
        getContentPane().add(RESButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 270, 30));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/front page.jpg"))); // NOI18N
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 520, 440));

        setSize(new java.awt.Dimension(525, 418));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButtonActionPerformed
        // TODO add your handling code here:
        Signup signup = new Signup();
        signup.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignupButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        LoginFrame login = new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton LoginButton;
    private keeptoo.KButton RESButton;
    private keeptoo.KButton SignupButton;
    private javax.swing.JLabel img;
    // End of variables declaration//GEN-END:variables
}
