
package login;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhammad Waseem
 */
public class KARAHI extends javax.swing.JFrame {

    
    /**
     * Creates new form KARAHI
     */
    
    private int Total_Amount = 0;
    
    public KARAHI() {
        initComponents();
    }

    
    
    
    public void Total_Karahi(int amount)
    {
        this.Total_Amount += amount;
    }
    
    
    public void Import_File()
    {
        String Filepath = "E:\\Rice.txt";
        File file = new File(Filepath);
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i=0;i<lines.length;i++)
            {
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
                
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Table2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void Export_File()
    {
        String Filepath = "E:\\Rice.txt";
        File file = new File(Filepath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i=0;i<jTable1.getRowCount();i++)
            {
                for(int j=0;j<jTable1.getColumnCount();j++)
                {
                    bw.write(jTable1.getValueAt(i, j).toString()+" ");
                }
                bw.newLine();
            }
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Table.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void Karahi(String name,int price)
    {
        String half_full[] = {"Half","Full"};
        JComboBox cb = new JComboBox(half_full);
        int Input = JOptionPane.showConfirmDialog(rootPane, cb,"Select Size",JOptionPane.DEFAULT_OPTION);
        if(Input == JOptionPane.OK_OPTION)
        {
            String size = (String)cb.getSelectedItem();
            
            if(size == "Half")
            {
                int Quantity = Integer.parseInt(JOptionPane.showInputDialog(null, "Quantity"));
                if (Quantity > 0) {
                    int Total = (price/2) * Quantity;
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.addRow(new Object[]{
                        name,
                        price/2,
                        Quantity,
                        Total

                    });
                    this.Total_Amount += Total;
                }
            }
            else
            {
                int Quantity = Integer.parseInt(JOptionPane.showInputDialog(null, "Quantity"));
                if (Quantity > 0) {
                    int Total = price * Quantity;
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.addRow(new Object[]{
                        name,
                        price,
                        Quantity,
                        Total

                    });
                    this.Total_Amount += Total;
                }
            }
            
        }
        
    }
    

    
//    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ALL_BUTTON1 = new javax.swing.JButton();
        BAR_B_Q_BUTTON2 = new javax.swing.JButton();
        KARAHI_BUTTON1 = new javax.swing.JButton();
        RICE_BUTTON1 = new javax.swing.JButton();
        VEGETABLES_BUTTON1 = new javax.swing.JButton();
        BEANS_BUTTON1 = new javax.swing.JButton();
        CHINES_DISHES_BUTTON1 = new javax.swing.JButton();
        FAST_FOOD_BUTTON1 = new javax.swing.JButton();
        SWEETS_BUTTON1 = new javax.swing.JButton();
        COLD_DRINKS_BUTTON1 = new javax.swing.JButton();
        TUNDOOR_BUTTON1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Chicken_Karahi_Pannel = new javax.swing.JPanel();
        Chicken_Karahi_Label = new javax.swing.JLabel();
        Chicken_Karahi_Price = new javax.swing.JLabel();
        Mutton_Karahi_Pannel = new javax.swing.JPanel();
        Mutton_Karahi_Label = new javax.swing.JLabel();
        Mutton_Karahi_Price = new javax.swing.JLabel();
        Chicken_Handi_Pannel = new javax.swing.JPanel();
        Chicken_Handi_Label = new javax.swing.JLabel();
        Chciken_Handi_Price = new javax.swing.JLabel();
        Mutton_Handi_Pannel = new javax.swing.JPanel();
        Mutton_Handi_Label = new javax.swing.JLabel();
        Mutton_Handi_Price = new javax.swing.JLabel();
        White_Chicken_Karahi_Pannel = new javax.swing.JPanel();
        White_Chicken_Karahi_Label = new javax.swing.JLabel();
        White_Chicken_Karahi_Price = new javax.swing.JLabel();
        Jelfarezi_Pannel = new javax.swing.JPanel();
        Jelfarezi_Label = new javax.swing.JLabel();
        Jelfarezi_Price = new javax.swing.JLabel();
        Chargha_Pannel = new javax.swing.JPanel();
        Chargha_Label = new javax.swing.JLabel();
        Chargha_Price = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Cash_Remained = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Total_TextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Cash_Recieved = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Delete_Row = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ALL_BUTTON1.setBackground(new java.awt.Color(51, 255, 51));
        ALL_BUTTON1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ALL_BUTTON1.setText("ALL PRODUCTS");
        ALL_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALL_BUTTON1ActionPerformed(evt);
            }
        });
        jPanel4.add(ALL_BUTTON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 150, 60));

        BAR_B_Q_BUTTON2.setBackground(new java.awt.Color(51, 255, 51));
        BAR_B_Q_BUTTON2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BAR_B_Q_BUTTON2.setText("BAR-B-Q");
        BAR_B_Q_BUTTON2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAR_B_Q_BUTTON2ActionPerformed(evt);
            }
        });
        jPanel4.add(BAR_B_Q_BUTTON2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 50));

        KARAHI_BUTTON1.setBackground(new java.awt.Color(51, 255, 51));
        KARAHI_BUTTON1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        KARAHI_BUTTON1.setText("KARAHI");
        KARAHI_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KARAHI_BUTTON1ActionPerformed(evt);
            }
        });
        jPanel4.add(KARAHI_BUTTON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 50));

        RICE_BUTTON1.setBackground(new java.awt.Color(51, 255, 51));
        RICE_BUTTON1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RICE_BUTTON1.setText("RICE");
        RICE_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RICE_BUTTON1ActionPerformed(evt);
            }
        });
        jPanel4.add(RICE_BUTTON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 50));

        VEGETABLES_BUTTON1.setBackground(new java.awt.Color(51, 255, 51));
        VEGETABLES_BUTTON1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        VEGETABLES_BUTTON1.setText("VEGETABLES");
        VEGETABLES_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VEGETABLES_BUTTON1ActionPerformed(evt);
            }
        });
        jPanel4.add(VEGETABLES_BUTTON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 50));

        BEANS_BUTTON1.setBackground(new java.awt.Color(51, 255, 51));
        BEANS_BUTTON1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BEANS_BUTTON1.setText("BEANS");
        BEANS_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEANS_BUTTON1ActionPerformed(evt);
            }
        });
        jPanel4.add(BEANS_BUTTON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 150, 50));

        CHINES_DISHES_BUTTON1.setBackground(new java.awt.Color(51, 255, 51));
        CHINES_DISHES_BUTTON1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CHINES_DISHES_BUTTON1.setText("CHINESE DISHES");
        CHINES_DISHES_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHINES_DISHES_BUTTON1ActionPerformed(evt);
            }
        });
        jPanel4.add(CHINES_DISHES_BUTTON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 150, 50));

        FAST_FOOD_BUTTON1.setBackground(new java.awt.Color(51, 255, 51));
        FAST_FOOD_BUTTON1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        FAST_FOOD_BUTTON1.setText("FAST FOOD");
        FAST_FOOD_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAST_FOOD_BUTTON1ActionPerformed(evt);
            }
        });
        jPanel4.add(FAST_FOOD_BUTTON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 150, 50));

        SWEETS_BUTTON1.setBackground(new java.awt.Color(51, 255, 51));
        SWEETS_BUTTON1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SWEETS_BUTTON1.setText("SWEETS");
        SWEETS_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SWEETS_BUTTON1ActionPerformed(evt);
            }
        });
        jPanel4.add(SWEETS_BUTTON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 150, 50));

        COLD_DRINKS_BUTTON1.setBackground(new java.awt.Color(51, 255, 51));
        COLD_DRINKS_BUTTON1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        COLD_DRINKS_BUTTON1.setText("COLD DRINKS");
        COLD_DRINKS_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COLD_DRINKS_BUTTON1ActionPerformed(evt);
            }
        });
        jPanel4.add(COLD_DRINKS_BUTTON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 150, 50));

        TUNDOOR_BUTTON1.setBackground(new java.awt.Color(51, 255, 51));
        TUNDOOR_BUTTON1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TUNDOOR_BUTTON1.setText("FROM TUNDOOR");
        TUNDOOR_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUNDOOR_BUTTON1ActionPerformed(evt);
            }
        });
        jPanel4.add(TUNDOOR_BUTTON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 150, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Karahi/Chicken Karahi.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Karahi/Mutton Karahi.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Karahi/Chicken Handi.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Karahi/Mutton Handi.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Karahi/White Chicken Karahi.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Karahi/Jalfrezi.jpg"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Karahi/Chargha.png"))); // NOI18N

        Chicken_Karahi_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Chicken_Karahi_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chicken_Karahi_PannelMouseClicked(evt);
            }
        });
        Chicken_Karahi_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Chicken_Karahi_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chicken_Karahi_Label.setForeground(new java.awt.Color(204, 0, 0));
        Chicken_Karahi_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken_Karahi_Label.setText("Chicken_Karahi");
        Chicken_Karahi_Pannel.add(Chicken_Karahi_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, -1));

        Chicken_Karahi_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chicken_Karahi_Price.setForeground(new java.awt.Color(204, 0, 0));
        Chicken_Karahi_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken_Karahi_Price.setText("Price = 750Rs.");
        Chicken_Karahi_Pannel.add(Chicken_Karahi_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 75, -1));

        Mutton_Karahi_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Mutton_Karahi_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mutton_Karahi_PannelMouseClicked(evt);
            }
        });
        Mutton_Karahi_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mutton_Karahi_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Mutton_Karahi_Label.setForeground(new java.awt.Color(204, 0, 0));
        Mutton_Karahi_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mutton_Karahi_Label.setText("Mutton_Karahi");
        Mutton_Karahi_Pannel.add(Mutton_Karahi_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 80, -1));

        Mutton_Karahi_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Mutton_Karahi_Price.setForeground(new java.awt.Color(204, 0, 0));
        Mutton_Karahi_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mutton_Karahi_Price.setText("Price = 1400Rs.");
        Mutton_Karahi_Pannel.add(Mutton_Karahi_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        Chicken_Handi_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Chicken_Handi_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chicken_Handi_PannelMouseClicked(evt);
            }
        });
        Chicken_Handi_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Chicken_Handi_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chicken_Handi_Label.setForeground(new java.awt.Color(204, 0, 0));
        Chicken_Handi_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken_Handi_Label.setText("Chicken_Handi");
        Chicken_Handi_Pannel.add(Chicken_Handi_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, 90, -1));

        Chciken_Handi_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chciken_Handi_Price.setForeground(new java.awt.Color(204, 0, 0));
        Chciken_Handi_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chciken_Handi_Price.setText("Price = 800Rs.");
        Chicken_Handi_Pannel.add(Chciken_Handi_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        Mutton_Handi_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Mutton_Handi_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mutton_Handi_PannelMouseClicked(evt);
            }
        });
        Mutton_Handi_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mutton_Handi_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Mutton_Handi_Label.setForeground(new java.awt.Color(204, 0, 0));
        Mutton_Handi_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mutton_Handi_Label.setText("Mutton_Handi");
        Mutton_Handi_Pannel.add(Mutton_Handi_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        Mutton_Handi_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Mutton_Handi_Price.setForeground(new java.awt.Color(204, 0, 0));
        Mutton_Handi_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mutton_Handi_Price.setText("Price = 1600Rs.");
        Mutton_Handi_Pannel.add(Mutton_Handi_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        White_Chicken_Karahi_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        White_Chicken_Karahi_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                White_Chicken_Karahi_PannelMouseClicked(evt);
            }
        });
        White_Chicken_Karahi_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        White_Chicken_Karahi_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        White_Chicken_Karahi_Label.setForeground(new java.awt.Color(204, 0, 0));
        White_Chicken_Karahi_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        White_Chicken_Karahi_Label.setText("White_Chicken_Karahi");
        White_Chicken_Karahi_Pannel.add(White_Chicken_Karahi_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 10, 120, -1));

        White_Chicken_Karahi_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        White_Chicken_Karahi_Price.setForeground(new java.awt.Color(204, 0, 0));
        White_Chicken_Karahi_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        White_Chicken_Karahi_Price.setText("Price = 750Rs.");
        White_Chicken_Karahi_Pannel.add(White_Chicken_Karahi_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        Jelfarezi_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Jelfarezi_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jelfarezi_PannelMouseClicked(evt);
            }
        });
        Jelfarezi_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jelfarezi_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Jelfarezi_Label.setForeground(new java.awt.Color(204, 0, 0));
        Jelfarezi_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jelfarezi_Label.setText("Jelfarezi");
        Jelfarezi_Pannel.add(Jelfarezi_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 74, -1));

        Jelfarezi_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Jelfarezi_Price.setForeground(new java.awt.Color(204, 0, 0));
        Jelfarezi_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jelfarezi_Price.setText("Price = 625Rs.");
        Jelfarezi_Pannel.add(Jelfarezi_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        Chargha_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Chargha_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chargha_PannelMouseClicked(evt);
            }
        });
        Chargha_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Chargha_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chargha_Label.setForeground(new java.awt.Color(204, 0, 0));
        Chargha_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chargha_Label.setText("Chargha");
        Chargha_Pannel.add(Chargha_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 74, -1));

        Chargha_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chargha_Price.setForeground(new java.awt.Color(204, 0, 0));
        Chargha_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chargha_Price.setText("Price = 650Rs.");
        Chargha_Pannel.add(Chargha_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        jPanel5.setBackground(new java.awt.Color(102, 255, 204));
        jPanel5.setLayout(null);

        Cash_Remained.setBackground(new java.awt.Color(153, 255, 153));
        Cash_Remained.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cash_Remained.setForeground(new java.awt.Color(204, 0, 0));
        jPanel5.add(Cash_Remained);
        Cash_Remained.setBounds(190, 130, 154, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Rs.");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(350, 90, 33, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Return");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(10, 130, 170, 30);

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Ready for Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(0, 0, 190, 40);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Total Price");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(10, 50, 170, 30);

        Total_TextField.setBackground(new java.awt.Color(153, 255, 153));
        Total_TextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Total_TextField.setForeground(new java.awt.Color(204, 0, 0));
        Total_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_TextFieldActionPerformed(evt);
            }
        });
        jPanel5.add(Total_TextField);
        Total_TextField.setBounds(190, 50, 154, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("Rs.");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(350, 130, 33, 32);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Cash Recieved");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(10, 90, 170, 30);

        Cash_Recieved.setBackground(new java.awt.Color(153, 255, 153));
        Cash_Recieved.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cash_Recieved.setForeground(new java.awt.Color(204, 0, 0));
        Cash_Recieved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cash_RecievedActionPerformed(evt);
            }
        });
        Cash_Recieved.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Cash_RecievedKeyPressed(evt);
            }
        });
        jPanel5.add(Cash_Recieved);
        Cash_Recieved.setBounds(190, 90, 154, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("Rs.");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(350, 50, 33, 30);

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Print Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(190, 170, 150, 50);

        Delete_Row.setBackground(new java.awt.Color(153, 255, 153));
        Delete_Row.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Delete_Row.setForeground(new java.awt.Color(204, 0, 0));
        Delete_Row.setText("Delete Some Item/Row");
        Delete_Row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_RowActionPerformed(evt);
            }
        });
        jPanel5.add(Delete_Row);
        Delete_Row.setBounds(270, 0, 190, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Chicken_Karahi_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(White_Chicken_Karahi_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Mutton_Karahi_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jelfarezi_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Chicken_Handi_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Chargha_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(Mutton_Handi_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 186, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Mutton_Handi_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Chicken_Karahi_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Mutton_Karahi_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Chicken_Handi_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)
                                                .addComponent(Chargha_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)
                                                .addComponent(Jelfarezi_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)
                                                .addComponent(White_Chicken_Karahi_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ALL_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALL_BUTTON1ActionPerformed
        // TODO add your handling code here:
        Export_File();
        All_Products all = new All_Products();
        all.Total_Products(this.Total_Amount);
        all.setVisible(true);
        this.dispose();
        all.Import_File();
    }//GEN-LAST:event_ALL_BUTTON1ActionPerformed

    private void BAR_B_Q_BUTTON2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAR_B_Q_BUTTON2ActionPerformed
        // TODO add your handling code here:
        Export_File();
        BAR_B_Q_Page b = new BAR_B_Q_Page();
        b.Total_BBQ(this.Total_Amount);
        b.setVisible(true);
        this.dispose();
        b.Import_File();
    }//GEN-LAST:event_BAR_B_Q_BUTTON2ActionPerformed

    private void KARAHI_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KARAHI_BUTTON1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KARAHI_BUTTON1ActionPerformed

    private void RICE_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RICE_BUTTON1ActionPerformed
        // TODO add your handling code here:
        Export_File();
        RICE rice = new RICE();
        rice.Total_Rice(this.Total_Amount);
        rice.setVisible(true);
        this.dispose();
        rice.Import_File();
    }//GEN-LAST:event_RICE_BUTTON1ActionPerformed

    private void VEGETABLES_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VEGETABLES_BUTTON1ActionPerformed
        // TODO add your handling code here:
        Export_File();
        VEGETABLES vege = new VEGETABLES();
        vege.Total_Vegetables(this.Total_Amount);
        vege.setVisible(true);
        this.dispose();
        vege.Import_File();
    }//GEN-LAST:event_VEGETABLES_BUTTON1ActionPerformed

    private void BEANS_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEANS_BUTTON1ActionPerformed
        // TODO add your handling code here:
        Export_File();
        BEANS beans = new BEANS();
        beans.Total_Beans(Total_Amount);
        beans.setVisible(true);
        this.dispose();
        beans.Import_File();
    }//GEN-LAST:event_BEANS_BUTTON1ActionPerformed

    private void CHINES_DISHES_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHINES_DISHES_BUTTON1ActionPerformed
        // TODO add your handling code here:
        Export_File();
        CHINESE_DISHES china = new CHINESE_DISHES();
        china.Total_Chinese_Dishes(Total_Amount);
        china.setVisible(true);
        this.dispose();
        china.Import_File();
    }//GEN-LAST:event_CHINES_DISHES_BUTTON1ActionPerformed

    private void FAST_FOOD_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAST_FOOD_BUTTON1ActionPerformed
        // TODO add your handling code here:
        Export_File();
        FAST_FOOD fast = new FAST_FOOD();
        fast.setVisible(true);
        fast.Total_Fast_Food(Total_Amount);
        this.dispose();
        fast.Import_File();
    }//GEN-LAST:event_FAST_FOOD_BUTTON1ActionPerformed

    private void SWEETS_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SWEETS_BUTTON1ActionPerformed
        // TODO add your handling code here:
        DESSERTS desserts = new DESSERTS();        
        desserts.setVisible(true);
        desserts.Total_Desserts(this.Total_Amount);
        this.dispose();
        desserts.Import_File();
    }//GEN-LAST:event_SWEETS_BUTTON1ActionPerformed

    private void COLD_DRINKS_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COLD_DRINKS_BUTTON1ActionPerformed
        // TODO add your handling code here:
        Export_File();
        BEVERAGES drinks = new BEVERAGES();
        drinks.setVisible(true);
        drinks.Total_Drinks(this.Total_Amount);
        this.dispose();
        drinks.Import_File();
    }//GEN-LAST:event_COLD_DRINKS_BUTTON1ActionPerformed

    private void TUNDOOR_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUNDOOR_BUTTON1ActionPerformed
        // TODO add your handling code here:
        Export_File();
        TUNDOOR roti = new TUNDOOR();
        roti.Total_Tundoor(this.Total_Amount);
        roti.setVisible(true);
        this.dispose();
        roti.Import_File();
    }//GEN-LAST:event_TUNDOOR_BUTTON1ActionPerformed

    
    
    
    
    
    private void Chicken_Karahi_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chicken_Karahi_PannelMouseClicked
        // TODO add your handling code here:
        String name = Chicken_Karahi_Label.getText();
        int price = 750;
        Karahi(name,price);       
    }//GEN-LAST:event_Chicken_Karahi_PannelMouseClicked

    private void Mutton_Karahi_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mutton_Karahi_PannelMouseClicked
        // TODO add your handling code here:
        String name = Mutton_Karahi_Label.getText();      
        int price = 1400;
        Karahi(name,price);       
        
    }//GEN-LAST:event_Mutton_Karahi_PannelMouseClicked

    private void Chicken_Handi_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chicken_Handi_PannelMouseClicked
        // TODO add your handling code here:
        String name = Chicken_Handi_Label.getText();       
        int price = 800;
        Karahi(name,price);       
        
    }//GEN-LAST:event_Chicken_Handi_PannelMouseClicked

    private void Mutton_Handi_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mutton_Handi_PannelMouseClicked
        // TODO add your handling code here:
        String name = Mutton_Handi_Label.getText();        
        int price = 1600;
        Karahi(name,price);       
    }//GEN-LAST:event_Mutton_Handi_PannelMouseClicked

    private void White_Chicken_Karahi_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_White_Chicken_Karahi_PannelMouseClicked
        // TODO add your handling code here:
        String name = White_Chicken_Karahi_Label.getText();
        int price = 750;
        Karahi(name,price);       
        
    }//GEN-LAST:event_White_Chicken_Karahi_PannelMouseClicked

    private void Jelfarezi_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jelfarezi_PannelMouseClicked
        // TODO add your handling code here:
        String name = Jelfarezi_Label.getText();
        int price = 625;
        Karahi(name,price);       
        
    }//GEN-LAST:event_Jelfarezi_PannelMouseClicked

    private void Chargha_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chargha_PannelMouseClicked
        // TODO add your handling code here:
        String name = Chargha_Label.getText();
        int price = 650;
        Karahi(name,price);       
    }//GEN-LAST:event_Chargha_PannelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Delete_Row.setEnabled(false);
        Total_TextField.setText("");
        Cash_Recieved.setText("");
        Cash_Remained.setText("");
        
        
        String Total = Integer.toString(this.Total_Amount);
        Total_TextField.setText(Total);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Total_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_TextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Total_TextFieldActionPerformed

    private void Cash_RecievedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cash_RecievedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cash_RecievedActionPerformed

    private void Cash_RecievedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cash_RecievedKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            String Cash = Cash_Recieved.getText();
            int Cash_Int = Integer.parseInt(Cash);
            int Remaining_Int = Cash_Int - this.Total_Amount;
            if (Remaining_Int > 0) 
            {
                String Remaining = Integer.toString(Remaining_Int);
                Cash_Remained.setText(Remaining);
            }
        }
    }//GEN-LAST:event_Cash_RecievedKeyPressed

    private void Delete_RowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_RowActionPerformed
        // TODO add your handling code here:
        Total_TextField.setText("");
        Cash_Recieved.setText("");
        Cash_Remained.setText("");
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int i = jTable1.getSelectedRow();
        
        
        String Filepath = "E:\\Restaurant-Managememt-System-Java\\Row_Price.txt";
        File file = new File(Filepath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            bw.write(jTable1.getValueAt(i, 3).toString());
            
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Table.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        if(jTable1.getSelectedRow()>=0)
        {
            model.removeRow(jTable1.getSelectedRow());      
        }
        else
        {
            JOptionPane.showMessageDialog(null, "First Select the Row!");
        }
        
       try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);

            Object[] lines = br.lines().toArray();
            String row ="";
            for(int k =0 ; k<lines.length; k++)
            {
                row += lines[k];
            }
            int row_int = 0;
            row_int = Integer.parseInt(row);
            this.Total_Amount -= row_int;
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(KARAHI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_Delete_RowActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Export_File();
        Bill bill = new Bill();
        bill.Total_Bill(this.Total_Amount,Cash_Recieved.getText(),Cash_Remained.getText());
        bill.setVisible(true);
        this.dispose();
        bill.Import_File();
    }//GEN-LAST:event_jButton2ActionPerformed
                   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KARAHI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KARAHI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KARAHI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KARAHI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KARAHI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ALL_BUTTON1;
    private javax.swing.JButton BAR_B_Q_BUTTON2;
    private javax.swing.JButton BEANS_BUTTON1;
    private javax.swing.JButton CHINES_DISHES_BUTTON1;
    private javax.swing.JButton COLD_DRINKS_BUTTON1;
    private javax.swing.JTextField Cash_Recieved;
    private javax.swing.JTextField Cash_Remained;
    private javax.swing.JLabel Chargha_Label;
    private javax.swing.JPanel Chargha_Pannel;
    private javax.swing.JLabel Chargha_Price;
    private javax.swing.JLabel Chciken_Handi_Price;
    private javax.swing.JLabel Chicken_Handi_Label;
    private javax.swing.JPanel Chicken_Handi_Pannel;
    private javax.swing.JLabel Chicken_Karahi_Label;
    private javax.swing.JPanel Chicken_Karahi_Pannel;
    private javax.swing.JLabel Chicken_Karahi_Price;
    private javax.swing.JButton Delete_Row;
    private javax.swing.JButton FAST_FOOD_BUTTON1;
    private javax.swing.JLabel Jelfarezi_Label;
    private javax.swing.JPanel Jelfarezi_Pannel;
    private javax.swing.JLabel Jelfarezi_Price;
    private javax.swing.JButton KARAHI_BUTTON1;
    private javax.swing.JLabel Mutton_Handi_Label;
    private javax.swing.JPanel Mutton_Handi_Pannel;
    private javax.swing.JLabel Mutton_Handi_Price;
    private javax.swing.JLabel Mutton_Karahi_Label;
    private javax.swing.JPanel Mutton_Karahi_Pannel;
    private javax.swing.JLabel Mutton_Karahi_Price;
    private javax.swing.JButton RICE_BUTTON1;
    private javax.swing.JButton SWEETS_BUTTON1;
    private javax.swing.JButton TUNDOOR_BUTTON1;
    private javax.swing.JTextField Total_TextField;
    private javax.swing.JButton VEGETABLES_BUTTON1;
    private javax.swing.JLabel White_Chicken_Karahi_Label;
    private javax.swing.JPanel White_Chicken_Karahi_Pannel;
    private javax.swing.JLabel White_Chicken_Karahi_Price;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
