package login;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class LoginFrame extends javax.swing.JFrame {

    private String name;
    private String password;
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }
    public void get(String username_from_signup,String password_from_signup)
    {
        this.name = username_from_signup; 
        this.password = password_from_signup;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserName_Label = new javax.swing.JLabel();
        panel_userName = new keeptoo.KGradientPanel();
        txt_userName = new javax.swing.JTextField();
        Password_Label = new javax.swing.JLabel();
        panel_password = new keeptoo.KGradientPanel();
        txt_password = new javax.swing.JPasswordField();
        account_label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_login = new keeptoo.KButton();
        img_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Management Solutions");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserName_Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UserName_Label.setText("Username");
        getContentPane().add(UserName_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        panel_userName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txt_userName.setBackground(new java.awt.Color(0,0,0,1));
        txt_userName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_userName.setForeground(new java.awt.Color(255, 255, 255));
        txt_userName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_userName.setToolTipText("Enter the username");
        txt_userName.setOpaque(false);
        txt_userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_userNameLayout = new javax.swing.GroupLayout(panel_userName);
        panel_userName.setLayout(panel_userNameLayout);
        panel_userNameLayout.setHorizontalGroup(
            panel_userNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_userName, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );
        panel_userNameLayout.setVerticalGroup(
            panel_userNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_userName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        getContentPane().add(panel_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 230, 40));

        Password_Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Password_Label.setText("Password");
        getContentPane().add(Password_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        panel_password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txt_password.setBackground(new java.awt.Color(0,0,0,1));
        txt_password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password.setToolTipText("Enter your password");
        txt_password.setCaretColor(new java.awt.Color(255, 0, 51));
        txt_password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout panel_passwordLayout = new javax.swing.GroupLayout(panel_password);
        panel_password.setLayout(panel_passwordLayout);
        panel_passwordLayout.setHorizontalGroup(
            panel_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );
        panel_passwordLayout.setVerticalGroup(
            panel_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        getContentPane().add(panel_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 230, 40));

        account_label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        account_label.setText("don't have an account Click");
        getContentPane().add(account_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 260, 160, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 204));
        jButton1.setText("here");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 257, 60, 20));

        btn_login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_login.setText("Login");
        btn_login.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_login.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_loginMouseEntered(evt);
            }
        });
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 120, 50));

        img_background.setBackground(new java.awt.Color(255, 255, 255));
        img_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/loginBackround.jpg"))); // NOI18N
        img_background.setText("jLabel1");
        getContentPane().add(img_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userNameActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:

        char[] enteredPasswordArray_Login = txt_password.getPassword();  // password enterd by user
        String enteredPasswordString_Login = "";
        String enteredUserNameString_Login = txt_userName.getText();
        for(int i=0; i < enteredPasswordArray_Login.length; i++) {
            enteredPasswordString_Login += enteredPasswordArray_Login[i];
        }
        if (enteredUserNameString_Login.equals(this.name) && enteredPasswordString_Login.equals(this.password)) 
        {
            Order_Type frame2 = new Order_Type();
            frame2.setVisible(true);
            this.dispose();
        }
        else 
        {
            JOptionPane.showMessageDialog(rootPane, "Wrong credentials !");
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loginMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Signup sign = new Signup();
        sign.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Password_Label;
    private javax.swing.JLabel UserName_Label;
    private javax.swing.JLabel account_label;
    private keeptoo.KButton btn_login;
    private javax.swing.JLabel img_background;
    private javax.swing.JButton jButton1;
    private keeptoo.KGradientPanel panel_password;
    private keeptoo.KGradientPanel panel_userName;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_userName;
    // End of variables declaration//GEN-END:variables
}
