/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhammad Waseem
 */
public class RICE extends javax.swing.JFrame {

    private int Total_Amount = 0;
    /**
     * Creates new form RICE
     */
    public RICE() {
        initComponents();
    }
    
    public void Total_Rice(int amount)
    {
        this.Total_Amount += amount;
    }
   
    public void Import_File()
    {
        String Filepath = "E:\\Rice.txt";
        File file = new File(Filepath);
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i=0;i<lines.length;i++)
            {
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Table2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void Export_File()
    {
        String Filepath = "E:\\Rice.txt";
        File file = new File(Filepath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i=0;i<jTable1.getRowCount();i++)
            {
                for(int j=0;j<jTable1.getColumnCount();j++)
                {
                    bw.write(jTable1.getValueAt(i, j).toString()+" ");
                }
                bw.newLine();
            }
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Table.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public void Rice(String name, int price)
    {
        String half_full[] = {"Half","Full"};
        JComboBox cb = new JComboBox(half_full);
        int Input = JOptionPane.showConfirmDialog(rootPane, cb,"Select Size",JOptionPane.DEFAULT_OPTION);
        if(Input == JOptionPane.OK_OPTION)
        {
            String size = (String)cb.getSelectedItem();
            
            if(size == "Half")
            {
                int Quantity = Integer.parseInt(JOptionPane.showInputDialog(null, "Quantity"));
                if (Quantity > 0) {
                    int Total = (price/2) * Quantity;
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.addRow(new Object[]{
                        name,
                        price/2,
                        Quantity,
                        Total

                    });
                    this.Total_Amount += Total;
                }
            }
            else
            {
                int Quantity = Integer.parseInt(JOptionPane.showInputDialog(null, "Quantity"));
                if (Quantity > 0) {
                    int Total = price * Quantity;
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.addRow(new Object[]{
                        name,
                        price,
                        Quantity,
                        Total

                    });
                    this.Total_Amount += Total;
                }
            }
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ALL_BUTTON = new javax.swing.JButton();
        BAR_B_Q_BUTTON1 = new javax.swing.JButton();
        KARAHI_BUTTON = new javax.swing.JButton();
        RICE_BUTTON = new javax.swing.JButton();
        VEGETABLES_BUTTON = new javax.swing.JButton();
        BEANS_BUTTON = new javax.swing.JButton();
        CHINES_DISHES_BUTTON = new javax.swing.JButton();
        FAST_FOOD_BUTTON = new javax.swing.JButton();
        SWEETS_BUTTON = new javax.swing.JButton();
        COLD_DRINKS_BUTTON = new javax.swing.JButton();
        TUNDOOR_BUTTON = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Daal_Chawal_Pannel = new javax.swing.JPanel();
        Daal_Chawal_Label = new javax.swing.JLabel();
        Chicken_Karahi_Price = new javax.swing.JLabel();
        Channa_Rice_Pannel = new javax.swing.JPanel();
        Mutton_Karahi_Label = new javax.swing.JLabel();
        Mutton_Karahi_Price = new javax.swing.JLabel();
        Chicken_Rice_Pannel = new javax.swing.JPanel();
        Channa_Rice_Label = new javax.swing.JLabel();
        Channa_Rice_Price = new javax.swing.JLabel();
        Vegetable_Rice_Pannel = new javax.swing.JPanel();
        Vegetable_Rice_Label = new javax.swing.JLabel();
        Vegetable_Rice_Price = new javax.swing.JLabel();
        Chinese_Rice_Pannel = new javax.swing.JPanel();
        Chinese_Rice_Label = new javax.swing.JLabel();
        Chinese_Rice_Price = new javax.swing.JLabel();
        Briyani_Pannel = new javax.swing.JPanel();
        Briyanii_Label = new javax.swing.JLabel();
        Briyani_Price = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Cash_Remained = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Total_TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Cash_Recieved = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Delete_Row = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ALL_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        ALL_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ALL_BUTTON.setText("ALL PRODUCTS");
        ALL_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALL_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(ALL_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        BAR_B_Q_BUTTON1.setBackground(new java.awt.Color(51, 255, 51));
        BAR_B_Q_BUTTON1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BAR_B_Q_BUTTON1.setText("BAR-B-Q");
        BAR_B_Q_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAR_B_Q_BUTTON1ActionPerformed(evt);
            }
        });
        jPanel2.add(BAR_B_Q_BUTTON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 50));

        KARAHI_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        KARAHI_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        KARAHI_BUTTON.setText("KARAHI");
        KARAHI_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KARAHI_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(KARAHI_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 50));

        RICE_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        RICE_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RICE_BUTTON.setText("RICE");
        RICE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RICE_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(RICE_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 50));

        VEGETABLES_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        VEGETABLES_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        VEGETABLES_BUTTON.setText("VEGETABLES");
        VEGETABLES_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VEGETABLES_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(VEGETABLES_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 50));

        BEANS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        BEANS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BEANS_BUTTON.setText("BEANS");
        BEANS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEANS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(BEANS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 150, 50));

        CHINES_DISHES_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        CHINES_DISHES_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CHINES_DISHES_BUTTON.setText("CHINESE DISHES");
        CHINES_DISHES_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHINES_DISHES_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(CHINES_DISHES_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 150, 50));

        FAST_FOOD_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        FAST_FOOD_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        FAST_FOOD_BUTTON.setText("FAST FOOD");
        FAST_FOOD_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAST_FOOD_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(FAST_FOOD_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 150, 50));

        SWEETS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        SWEETS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SWEETS_BUTTON.setText("DESSERTS");
        SWEETS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SWEETS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(SWEETS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 150, 50));

        COLD_DRINKS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        COLD_DRINKS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        COLD_DRINKS_BUTTON.setText("BEVERAGES");
        COLD_DRINKS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COLD_DRINKS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(COLD_DRINKS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 150, 50));

        TUNDOOR_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        TUNDOOR_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TUNDOOR_BUTTON.setText("FROM TUNDOOR");
        TUNDOOR_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUNDOOR_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(TUNDOOR_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 150, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Rice/Daal Rice.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Rice/Channa Rice.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Rice/Chicken Rice.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Vegetable Pulao.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Rice/Chinese Rice.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Rice/Briyani.jpg"))); // NOI18N

        Daal_Chawal_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Daal_Chawal_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Daal_Chawal_PannelMouseClicked(evt);
            }
        });
        Daal_Chawal_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Daal_Chawal_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Daal_Chawal_Label.setForeground(new java.awt.Color(204, 0, 0));
        Daal_Chawal_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Daal_Chawal_Label.setText("Daal_Rice");
        Daal_Chawal_Pannel.add(Daal_Chawal_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, -1));

        Chicken_Karahi_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chicken_Karahi_Price.setForeground(new java.awt.Color(204, 0, 0));
        Chicken_Karahi_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken_Karahi_Price.setText("Price = 150Rs.");
        Daal_Chawal_Pannel.add(Chicken_Karahi_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, -1));

        Channa_Rice_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Channa_Rice_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Channa_Rice_PannelMouseClicked(evt);
            }
        });
        Channa_Rice_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mutton_Karahi_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Mutton_Karahi_Label.setForeground(new java.awt.Color(204, 0, 0));
        Mutton_Karahi_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mutton_Karahi_Label.setText("Channa_Rice");
        Channa_Rice_Pannel.add(Mutton_Karahi_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        Mutton_Karahi_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Mutton_Karahi_Price.setForeground(new java.awt.Color(204, 0, 0));
        Mutton_Karahi_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mutton_Karahi_Price.setText("Price = 120Rs.");
        Channa_Rice_Pannel.add(Mutton_Karahi_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        Chicken_Rice_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Chicken_Rice_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chicken_Rice_PannelMouseClicked(evt);
            }
        });
        Chicken_Rice_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Channa_Rice_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Channa_Rice_Label.setForeground(new java.awt.Color(204, 0, 0));
        Channa_Rice_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Channa_Rice_Label.setText("Chicken_Rice");
        Chicken_Rice_Pannel.add(Channa_Rice_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, 90, -1));

        Channa_Rice_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Channa_Rice_Price.setForeground(new java.awt.Color(204, 0, 0));
        Channa_Rice_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Channa_Rice_Price.setText("Price = 180Rs.");
        Chicken_Rice_Pannel.add(Channa_Rice_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 30, 80, -1));

        Vegetable_Rice_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Vegetable_Rice_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Vegetable_Rice_PannelMouseClicked(evt);
            }
        });
        Vegetable_Rice_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Vegetable_Rice_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Vegetable_Rice_Label.setForeground(new java.awt.Color(204, 0, 0));
        Vegetable_Rice_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Vegetable_Rice_Label.setText("Vegetable_Rice");
        Vegetable_Rice_Pannel.add(Vegetable_Rice_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        Vegetable_Rice_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Vegetable_Rice_Price.setForeground(new java.awt.Color(204, 0, 0));
        Vegetable_Rice_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Vegetable_Rice_Price.setText("Price = 180Rs.");
        Vegetable_Rice_Pannel.add(Vegetable_Rice_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, -1));

        Chinese_Rice_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Chinese_Rice_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chinese_Rice_PannelMouseClicked(evt);
            }
        });
        Chinese_Rice_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Chinese_Rice_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chinese_Rice_Label.setForeground(new java.awt.Color(204, 0, 0));
        Chinese_Rice_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chinese_Rice_Label.setText("Chinese_Rice");
        Chinese_Rice_Pannel.add(Chinese_Rice_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 10, 120, -1));

        Chinese_Rice_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Chinese_Rice_Price.setForeground(new java.awt.Color(204, 0, 0));
        Chinese_Rice_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chinese_Rice_Price.setText("Price = 200Rs.");
        Chinese_Rice_Pannel.add(Chinese_Rice_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        Briyani_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Briyani_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Briyani_PannelMouseClicked(evt);
            }
        });
        Briyani_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Briyanii_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Briyanii_Label.setForeground(new java.awt.Color(204, 0, 0));
        Briyanii_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Briyanii_Label.setText("Briyani");
        Briyani_Pannel.add(Briyanii_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 74, -1));

        Briyani_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Briyani_Price.setForeground(new java.awt.Color(204, 0, 0));
        Briyani_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Briyani_Price.setText("Price = 250Rs.");
        Briyani_Pannel.add(Briyani_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        jPanel3.setBackground(new java.awt.Color(102, 255, 204));
        jPanel3.setLayout(null);

        Cash_Remained.setBackground(new java.awt.Color(153, 255, 153));
        Cash_Remained.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cash_Remained.setForeground(new java.awt.Color(204, 0, 0));
        jPanel3.add(Cash_Remained);
        Cash_Remained.setBounds(190, 130, 154, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Rs.");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(350, 90, 33, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Return");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 130, 170, 30);

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Ready for Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(0, 0, 190, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total Price");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 50, 170, 30);

        Total_TextField.setBackground(new java.awt.Color(153, 255, 153));
        Total_TextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Total_TextField.setForeground(new java.awt.Color(204, 0, 0));
        Total_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_TextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(Total_TextField);
        Total_TextField.setBounds(190, 50, 154, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Rs.");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(350, 130, 33, 32);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cash Recieved");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 90, 170, 30);

        Cash_Recieved.setBackground(new java.awt.Color(153, 255, 153));
        Cash_Recieved.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cash_Recieved.setForeground(new java.awt.Color(204, 0, 0));
        Cash_Recieved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cash_RecievedActionPerformed(evt);
            }
        });
        Cash_Recieved.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Cash_RecievedKeyPressed(evt);
            }
        });
        jPanel3.add(Cash_Recieved);
        Cash_Recieved.setBounds(190, 90, 154, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Rs.");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(350, 50, 33, 30);

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Print Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(190, 170, 150, 50);

        Delete_Row.setBackground(new java.awt.Color(153, 255, 153));
        Delete_Row.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Delete_Row.setForeground(new java.awt.Color(204, 0, 0));
        Delete_Row.setText("Delete Some Item/Row");
        Delete_Row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_RowActionPerformed(evt);
            }
        });
        jPanel3.add(Delete_Row);
        Delete_Row.setBounds(270, 0, 190, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Daal_Chawal_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Chinese_Rice_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Channa_Rice_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Chicken_Rice_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Vegetable_Rice_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Briyani_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Vegetable_Rice_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Daal_Chawal_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Channa_Rice_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Chicken_Rice_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Briyani_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Chinese_Rice_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ALL_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALL_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        All_Products all = new All_Products();
        all.Total_Products(this.Total_Amount);
        all.setVisible(true);
        this.dispose();
        all.Import_File();
    }//GEN-LAST:event_ALL_BUTTONActionPerformed

    private void BAR_B_Q_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAR_B_Q_BUTTON1ActionPerformed
        // TODO add your handling code here:
        Export_File();
        BAR_B_Q_Page b = new BAR_B_Q_Page();
        b.Total_BBQ(this.Total_Amount);
        b.setVisible(true);
        this.dispose();
        b.Import_File();
    }//GEN-LAST:event_BAR_B_Q_BUTTON1ActionPerformed

    private void KARAHI_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KARAHI_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        KARAHI K =new KARAHI();
        K.Total_Karahi(this.Total_Amount);
        K.setVisible(true);
        this.dispose();
        K.Import_File();
    }//GEN-LAST:event_KARAHI_BUTTONActionPerformed

    private void RICE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RICE_BUTTONActionPerformed
        // TODO add your handling code here:       
    }//GEN-LAST:event_RICE_BUTTONActionPerformed

    private void VEGETABLES_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VEGETABLES_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        VEGETABLES vege = new VEGETABLES();
        vege.Total_Vegetables(this.Total_Amount);
        vege.setVisible(true);
        this.dispose();   
        vege.Import_File();
    }//GEN-LAST:event_VEGETABLES_BUTTONActionPerformed

    private void BEANS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEANS_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        BEANS beans = new BEANS();
        beans.Total_Beans(this.Total_Amount);
        beans.setVisible(true);
        this.dispose();
        beans.Import_File();
    }//GEN-LAST:event_BEANS_BUTTONActionPerformed

    private void CHINES_DISHES_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHINES_DISHES_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        CHINESE_DISHES china = new CHINESE_DISHES();
        china.Total_Chinese_Dishes(this.Total_Amount);
        china.setVisible(true);
        this.dispose();
        china.Import_File();
    }//GEN-LAST:event_CHINES_DISHES_BUTTONActionPerformed

    private void FAST_FOOD_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAST_FOOD_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        FAST_FOOD fast = new FAST_FOOD();
        fast.Total_Fast_Food(this.Total_Amount);
        fast.setVisible(true);
        this.dispose();
        fast.Import_File();
    }//GEN-LAST:event_FAST_FOOD_BUTTONActionPerformed

    private void SWEETS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SWEETS_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        DESSERTS desserts = new DESSERTS();
        desserts.Total_Desserts(this.Total_Amount);
        desserts.setVisible(true);
        this.dispose();
        desserts.Import_File();
    }//GEN-LAST:event_SWEETS_BUTTONActionPerformed

    private void COLD_DRINKS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COLD_DRINKS_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        BEVERAGES drinks = new BEVERAGES();
        drinks.Total_Drinks(this.Total_Amount);
        drinks.setVisible(true);
        this.dispose();
        drinks.Import_File();
    }//GEN-LAST:event_COLD_DRINKS_BUTTONActionPerformed

    private void TUNDOOR_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUNDOOR_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        TUNDOOR roti = new TUNDOOR();
        roti.Total_Tundoor(this.Total_Amount);
        roti.setVisible(true);
        this.dispose();
        roti.Import_File();
    }//GEN-LAST:event_TUNDOOR_BUTTONActionPerformed

    
    
    private void Daal_Chawal_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Daal_Chawal_PannelMouseClicked
        // TODO add your handling code here:
        String name = Daal_Chawal_Label.getText();

        int price = 150;
        Rice(name,price);

    }//GEN-LAST:event_Daal_Chawal_PannelMouseClicked

    private void Channa_Rice_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Channa_Rice_PannelMouseClicked
        // TODO add your handling code here:
        String name = Mutton_Karahi_Label.getText();

        int price = 120;
        Rice(name,price);
        

    }//GEN-LAST:event_Channa_Rice_PannelMouseClicked

    private void Chicken_Rice_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chicken_Rice_PannelMouseClicked
        // TODO add your handling code here:
        String name = Channa_Rice_Label.getText();

        int price = 180;
        Rice(name,price);
        

    }//GEN-LAST:event_Chicken_Rice_PannelMouseClicked

    private void Vegetable_Rice_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Vegetable_Rice_PannelMouseClicked
        // TODO add your handling code here:
        String name = Vegetable_Rice_Label.getText();
        int price = 180;
        Rice(name,price);
    }//GEN-LAST:event_Vegetable_Rice_PannelMouseClicked

    private void Chinese_Rice_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chinese_Rice_PannelMouseClicked
        // TODO add your handling code here:
        String name = Chinese_Rice_Label.getText();
        int price = 200;
        Rice(name,price);
    }//GEN-LAST:event_Chinese_Rice_PannelMouseClicked

    private void Briyani_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Briyani_PannelMouseClicked
        // TODO add your handling code here:
        String name = Briyanii_Label.getText();
        int price = 250;
        Rice(name,price);
        

    }//GEN-LAST:event_Briyani_PannelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Delete_Row.setEnabled(false);
        Total_TextField.setText("");
        Cash_Recieved.setText("");
        Cash_Remained.setText("");

        String Total = Integer.toString(this.Total_Amount);
        Total_TextField.setText(Total);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Total_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_TextFieldActionPerformed

    private void Cash_RecievedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cash_RecievedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cash_RecievedActionPerformed

    private void Cash_RecievedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cash_RecievedKeyPressed
        // TODO add your handling code here:

        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {

            String Cash = Cash_Recieved.getText();
            int Cash_Int = Integer.parseInt(Cash);
            int Remaining_Int = Cash_Int - this.Total_Amount;
            if (Remaining_Int > 0) 
            {
                String Remaining = Integer.toString(Remaining_Int);
                Cash_Remained.setText(Remaining);
            }

        }
    }//GEN-LAST:event_Cash_RecievedKeyPressed

    private void Delete_RowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_RowActionPerformed
        // TODO add your handling code here:
        Total_TextField.setText("");
        Cash_Recieved.setText("");
        Cash_Remained.setText("");
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int i = jTable1.getSelectedRow();
        
        
        String Filepath = "E:\\Restaurant-Managememt-System-Java\\Row_Price.txt";
        File file = new File(Filepath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            bw.write(jTable1.getValueAt(i, 3).toString());
            
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Table.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        if(jTable1.getSelectedRow()>=0)
        {
            model.removeRow(jTable1.getSelectedRow());      
        }
        else
        {
            JOptionPane.showMessageDialog(null, "First Select the Row!");
        }
        
       try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);

            Object[] lines = br.lines().toArray();
            String row ="";
            for(int k =0 ; k<lines.length; k++)
            {
                row += lines[k];
            }
            int row_int = 0;
            row_int = Integer.parseInt(row);
            this.Total_Amount -= row_int;
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(KARAHI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Delete_RowActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Export_File();
        Bill bill = new Bill();
        bill.Total_Bill(this.Total_Amount,Cash_Recieved.getText(),Cash_Remained.getText());
        bill.setVisible(true);
        bill.Import_File();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RICE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ALL_BUTTON;
    private javax.swing.JButton BAR_B_Q_BUTTON1;
    private javax.swing.JButton BEANS_BUTTON;
    private javax.swing.JPanel Briyani_Pannel;
    private javax.swing.JLabel Briyani_Price;
    private javax.swing.JLabel Briyanii_Label;
    private javax.swing.JButton CHINES_DISHES_BUTTON;
    private javax.swing.JButton COLD_DRINKS_BUTTON;
    private javax.swing.JTextField Cash_Recieved;
    private javax.swing.JTextField Cash_Remained;
    private javax.swing.JLabel Channa_Rice_Label;
    private javax.swing.JPanel Channa_Rice_Pannel;
    private javax.swing.JLabel Channa_Rice_Price;
    private javax.swing.JLabel Chicken_Karahi_Price;
    private javax.swing.JPanel Chicken_Rice_Pannel;
    private javax.swing.JLabel Chinese_Rice_Label;
    private javax.swing.JPanel Chinese_Rice_Pannel;
    private javax.swing.JLabel Chinese_Rice_Price;
    private javax.swing.JLabel Daal_Chawal_Label;
    private javax.swing.JPanel Daal_Chawal_Pannel;
    private javax.swing.JButton Delete_Row;
    private javax.swing.JButton FAST_FOOD_BUTTON;
    private javax.swing.JButton KARAHI_BUTTON;
    private javax.swing.JLabel Mutton_Karahi_Label;
    private javax.swing.JLabel Mutton_Karahi_Price;
    private javax.swing.JButton RICE_BUTTON;
    private javax.swing.JButton SWEETS_BUTTON;
    private javax.swing.JButton TUNDOOR_BUTTON;
    private javax.swing.JTextField Total_TextField;
    private javax.swing.JButton VEGETABLES_BUTTON;
    private javax.swing.JLabel Vegetable_Rice_Label;
    private javax.swing.JPanel Vegetable_Rice_Pannel;
    private javax.swing.JLabel Vegetable_Rice_Price;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
