/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Waseem
 */
public class Signup extends javax.swing.JFrame {

    public String name;
    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UserNamePanel = new keeptoo.KGradientPanel();
        Username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PasswordPanel = new keeptoo.KGradientPanel();
        Passwordfield = new javax.swing.JPasswordField();
        btn_login = new keeptoo.KButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        UserNamePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Username.setBackground(new java.awt.Color(0,0,0,1));
        Username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Username.setToolTipText("Set UserName");
        Username.setOpaque(false);
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserNamePanelLayout = new javax.swing.GroupLayout(UserNamePanel);
        UserNamePanel.setLayout(UserNamePanelLayout);
        UserNamePanelLayout.setHorizontalGroup(
            UserNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
            .addGroup(UserNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserNamePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Username, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)))
        );
        UserNamePanelLayout.setVerticalGroup(
            UserNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(UserNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Username, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        getContentPane().add(UserNamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 230, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        PasswordPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Passwordfield.setBackground(new java.awt.Color(0,0,0,1));
        Passwordfield.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Passwordfield.setForeground(new java.awt.Color(255, 255, 255));
        Passwordfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Passwordfield.setOpaque(false);
        Passwordfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordfieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout PasswordPanelLayout = new javax.swing.GroupLayout(PasswordPanel);
        PasswordPanel.setLayout(PasswordPanelLayout);
        PasswordPanelLayout.setHorizontalGroup(
            PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
            .addGroup(PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Passwordfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
        );
        PasswordPanelLayout.setVerticalGroup(
            PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Passwordfield, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        getContentPane().add(PasswordPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 230, 40));

        btn_login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_login.setText("Sign up");
        btn_login.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_login.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_loginMouseEntered(evt);
            }
        });
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 120, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginBackround.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loginMouseEntered

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        String Name = Username.getText();  //UserName set by User
               
        char[] enteredPasswordarray_Signup = Passwordfield.getPassword(); // Password entered by User
        
        //If there are less than 8 characters in Password
        if (Passwordfield.getPassword().length < 8) 
        {
            JOptionPane.showMessageDialog(rootPane, "Please Enter at least 8 Characters");
        } 
        //If there are more than or equals to 8 characters in Password
        else 
        {
            int number_count = 0;
            int alphabet_count = 0;
            //Counting Numbers in Password
            for (int i = 0; i < enteredPasswordarray_Signup.length; i++) 
            {
                for (int j = 48; j <= 57; j++) 
                {
                    if (enteredPasswordarray_Signup[i] == (char) j) 
                    {
                        number_count++;
                    }
                }
            }
            //Counting Characters in Password
            for (int i = 0; i < enteredPasswordarray_Signup.length; i++) 
            {
                for (int j = 0; j <= 47; j++) 
                {
                    if (enteredPasswordarray_Signup[i] == (char) j) 
                    {
                        alphabet_count++;
                    }
                    if (j == 47) 
                    {
                        for (j = 58; j <= 127; j++) 
                        {
                            if (enteredPasswordarray_Signup[i] == (char) j) 
                            {
                                alphabet_count++;
                            }
                        }
                    }
                }
            }
            //If there is no Number in Password
            if (number_count == 0) 
            {
                JOptionPane.showMessageDialog(rootPane, "Please Enter at least 1 Number");
            }
            //If there is no Character in Password
            if (alphabet_count == 0) 
            {
                JOptionPane.showMessageDialog(rootPane, "Please Enter at least 1 Alphabetic Character");
            }
            //If both Numbers and Characters are present in Password 
            if (number_count != 0 && alphabet_count != 0) 
            {         
                //Used to change our password in String
                String enteredPasswordString_Signup = "";

                for (int k = 0; k < enteredPasswordarray_Signup.length; k++) 
                {
                    enteredPasswordString_Signup += enteredPasswordarray_Signup[k];
                }
                //Login page is calling
                LoginFrame login = new LoginFrame();
                //UserName and Password are going to Login Page for Confirmation 
                login.get(Name, enteredPasswordString_Signup);
                login.setVisible(true);
                this.dispose(); //It is used if we want to open next page in same not in other page       
                this.name = Name;
                
           }  

        }

               
    }//GEN-LAST:event_btn_loginActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_UsernameActionPerformed

    private void PasswordfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordfieldKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PasswordfieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel PasswordPanel;
    private javax.swing.JPasswordField Passwordfield;
    private keeptoo.KGradientPanel UserNamePanel;
    private javax.swing.JTextField Username;
    private keeptoo.KButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
