/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhammad Waseem
 */
public class TUNDOOR extends javax.swing.JFrame {

    private int Total_Amount = 0;
    /**
     * Creates new form TUNDOOR
     */
    public TUNDOOR() {
        initComponents();
    }

    
    public void Total_Tundoor(int amount)
    {
        this.Total_Amount += amount; 
    }
    
    public void Import_File()
    {
        String Filepath = "E:\\Rice.txt";
        File file = new File(Filepath);
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i=0;i<lines.length;i++)
            {
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Table2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void Export_File()
    {
        String Filepath = "E:\\Rice.txt";
        File file = new File(Filepath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i=0;i<jTable1.getRowCount();i++)
            {
                for(int j=0;j<jTable1.getColumnCount();j++)
                {
                    bw.write(jTable1.getValueAt(i, j).toString()+" ");
                }
                bw.newLine();
            }
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Table.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void Tundoor(String name, int price)
    {

        int Quantity = Integer.parseInt(JOptionPane.showInputDialog(null, "Quantity"));
        if (Quantity > 0) 
        {
            int Total = price * Quantity;
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]
            {
                name,
                price,
                Quantity,
                Total

            });
                    this.Total_Amount += Total;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ALL_BUTTON = new javax.swing.JButton();
        BAR_B_Q_BUTTON1 = new javax.swing.JButton();
        KARAHI_BUTTON = new javax.swing.JButton();
        RICE_BUTTON = new javax.swing.JButton();
        VEGETABLES_BUTTON = new javax.swing.JButton();
        BEANS_BUTTON = new javax.swing.JButton();
        CHINES_DISHES_BUTTON = new javax.swing.JButton();
        FAST_FOOD_BUTTON = new javax.swing.JButton();
        SWEETS_BUTTON = new javax.swing.JButton();
        COLD_DRINKS_BUTTON = new javax.swing.JButton();
        TUNDOOR_BUTTON = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        Cash_Remained = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Total_TextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Cash_Recieved = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Delete_Row = new javax.swing.JButton();
        Simple_Roti_Pannel = new javax.swing.JPanel();
        Simple_Roti_Label = new javax.swing.JLabel();
        Simple_Roti_Price = new javax.swing.JLabel();
        Paratha_Pannel = new javax.swing.JPanel();
        Paratha_Label = new javax.swing.JLabel();
        Paratha_Price = new javax.swing.JLabel();
        Simple_Naan_Pannel = new javax.swing.JPanel();
        Simple_Naan_Label = new javax.swing.JLabel();
        Simple_Naan_Price = new javax.swing.JLabel();
        Rogni_Naan_Pannel = new javax.swing.JPanel();
        Rogni_Naan_Label = new javax.swing.JLabel();
        Rogni_Naan_Price = new javax.swing.JLabel();
        Khameere_Roti_Pannel = new javax.swing.JPanel();
        Khameere_Roti_Label = new javax.swing.JLabel();
        Khameere_Roti_Price = new javax.swing.JLabel();
        Alo_Wala_Naan_Pannel = new javax.swing.JPanel();
        Alo_Wala_Naan_Label = new javax.swing.JLabel();
        Alo_Wala_Naan_Price = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ALL_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        ALL_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ALL_BUTTON.setText("ALL PRODUCTS");
        ALL_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALL_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(ALL_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        BAR_B_Q_BUTTON1.setBackground(new java.awt.Color(51, 255, 51));
        BAR_B_Q_BUTTON1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BAR_B_Q_BUTTON1.setText("BAR-B-Q");
        BAR_B_Q_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAR_B_Q_BUTTON1ActionPerformed(evt);
            }
        });
        jPanel2.add(BAR_B_Q_BUTTON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 50));

        KARAHI_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        KARAHI_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        KARAHI_BUTTON.setText("KARAHI");
        KARAHI_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KARAHI_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(KARAHI_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 50));

        RICE_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        RICE_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RICE_BUTTON.setText("RICE");
        RICE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RICE_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(RICE_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 50));

        VEGETABLES_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        VEGETABLES_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        VEGETABLES_BUTTON.setText("VEGETABLES");
        VEGETABLES_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VEGETABLES_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(VEGETABLES_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 50));

        BEANS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        BEANS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BEANS_BUTTON.setText("BEANS");
        BEANS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEANS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(BEANS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 150, 50));

        CHINES_DISHES_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        CHINES_DISHES_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CHINES_DISHES_BUTTON.setText("CHINESE DISHES");
        CHINES_DISHES_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHINES_DISHES_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(CHINES_DISHES_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 150, 50));

        FAST_FOOD_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        FAST_FOOD_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        FAST_FOOD_BUTTON.setText("FAST FOOD");
        FAST_FOOD_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAST_FOOD_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(FAST_FOOD_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 150, 50));

        SWEETS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        SWEETS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SWEETS_BUTTON.setText("SWEETS");
        SWEETS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SWEETS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(SWEETS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 150, 50));

        COLD_DRINKS_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        COLD_DRINKS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        COLD_DRINKS_BUTTON.setText("COLD DRINKS");
        COLD_DRINKS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COLD_DRINKS_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(COLD_DRINKS_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 150, 50));

        TUNDOOR_BUTTON.setBackground(new java.awt.Color(51, 255, 51));
        TUNDOOR_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TUNDOOR_BUTTON.setText("FROM TUNDOOR");
        TUNDOOR_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUNDOOR_BUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(TUNDOOR_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 150, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel4.setBackground(new java.awt.Color(102, 255, 204));
        jPanel4.setLayout(null);

        Cash_Remained.setBackground(new java.awt.Color(153, 255, 153));
        Cash_Remained.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cash_Remained.setForeground(new java.awt.Color(204, 0, 0));
        jPanel4.add(Cash_Remained);
        Cash_Remained.setBounds(190, 130, 154, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Rs.");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(350, 90, 34, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Return");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 130, 170, 30);

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Ready for Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(0, 0, 190, 40);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Total Price");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(10, 50, 170, 30);

        Total_TextField.setBackground(new java.awt.Color(153, 255, 153));
        Total_TextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Total_TextField.setForeground(new java.awt.Color(204, 0, 0));
        Total_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_TextFieldActionPerformed(evt);
            }
        });
        jPanel4.add(Total_TextField);
        Total_TextField.setBounds(190, 50, 154, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("Rs.");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(350, 130, 34, 32);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Cash Recieved");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(10, 90, 170, 30);

        Cash_Recieved.setBackground(new java.awt.Color(153, 255, 153));
        Cash_Recieved.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cash_Recieved.setForeground(new java.awt.Color(204, 0, 0));
        Cash_Recieved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cash_RecievedActionPerformed(evt);
            }
        });
        Cash_Recieved.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Cash_RecievedKeyPressed(evt);
            }
        });
        jPanel4.add(Cash_Recieved);
        Cash_Recieved.setBounds(190, 90, 154, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("Rs.");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(350, 50, 34, 30);

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Print Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(190, 170, 150, 50);

        Delete_Row.setBackground(new java.awt.Color(153, 255, 153));
        Delete_Row.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Delete_Row.setForeground(new java.awt.Color(204, 0, 0));
        Delete_Row.setText("Delete Some Item/Row");
        Delete_Row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_RowActionPerformed(evt);
            }
        });
        jPanel4.add(Delete_Row);
        Delete_Row.setBounds(270, 0, 190, 40);

        Simple_Roti_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Simple_Roti_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Simple_Roti_PannelMouseClicked(evt);
            }
        });
        Simple_Roti_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Simple_Roti_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Simple_Roti_Label.setForeground(new java.awt.Color(204, 0, 0));
        Simple_Roti_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Simple_Roti_Label.setText("Simple_Roti");
        Simple_Roti_Pannel.add(Simple_Roti_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, -1));

        Simple_Roti_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Simple_Roti_Price.setForeground(new java.awt.Color(204, 0, 0));
        Simple_Roti_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Simple_Roti_Price.setText("Price = 5Rs.");
        Simple_Roti_Pannel.add(Simple_Roti_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 75, -1));

        Paratha_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Paratha_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Paratha_PannelMouseClicked(evt);
            }
        });
        Paratha_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Paratha_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Paratha_Label.setForeground(new java.awt.Color(204, 0, 0));
        Paratha_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Paratha_Label.setText("Paratha");
        Paratha_Pannel.add(Paratha_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        Paratha_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Paratha_Price.setForeground(new java.awt.Color(204, 0, 0));
        Paratha_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Paratha_Price.setText("Price = 20Rs.");
        Paratha_Pannel.add(Paratha_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        Simple_Naan_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Simple_Naan_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Simple_Naan_PannelMouseClicked(evt);
            }
        });
        Simple_Naan_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Simple_Naan_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Simple_Naan_Label.setForeground(new java.awt.Color(204, 0, 0));
        Simple_Naan_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Simple_Naan_Label.setText("Simple_Naan");
        Simple_Naan_Pannel.add(Simple_Naan_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, 90, -1));

        Simple_Naan_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Simple_Naan_Price.setForeground(new java.awt.Color(204, 0, 0));
        Simple_Naan_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Simple_Naan_Price.setText("Price = 10Rs.");
        Simple_Naan_Pannel.add(Simple_Naan_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        Rogni_Naan_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Rogni_Naan_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rogni_Naan_PannelMouseClicked(evt);
            }
        });
        Rogni_Naan_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Rogni_Naan_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Rogni_Naan_Label.setForeground(new java.awt.Color(204, 0, 0));
        Rogni_Naan_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Rogni_Naan_Label.setText("Rogni_Naan");
        Rogni_Naan_Pannel.add(Rogni_Naan_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        Rogni_Naan_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Rogni_Naan_Price.setForeground(new java.awt.Color(204, 0, 0));
        Rogni_Naan_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Rogni_Naan_Price.setText("Price = 20Rs.");
        Rogni_Naan_Pannel.add(Rogni_Naan_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, -1));

        Khameere_Roti_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Khameere_Roti_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Khameere_Roti_PannelMouseClicked(evt);
            }
        });
        Khameere_Roti_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Khameere_Roti_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Khameere_Roti_Label.setForeground(new java.awt.Color(204, 0, 0));
        Khameere_Roti_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Khameere_Roti_Label.setText("Khameere_Roti");
        Khameere_Roti_Pannel.add(Khameere_Roti_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 10, 120, -1));

        Khameere_Roti_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Khameere_Roti_Price.setForeground(new java.awt.Color(204, 0, 0));
        Khameere_Roti_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Khameere_Roti_Price.setText("Price = 7Rs.");
        Khameere_Roti_Pannel.add(Khameere_Roti_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 74, -1));

        Alo_Wala_Naan_Pannel.setBackground(new java.awt.Color(204, 204, 0));
        Alo_Wala_Naan_Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Alo_Wala_Naan_PannelMouseClicked(evt);
            }
        });
        Alo_Wala_Naan_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Alo_Wala_Naan_Label.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Alo_Wala_Naan_Label.setForeground(new java.awt.Color(204, 0, 0));
        Alo_Wala_Naan_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Alo_Wala_Naan_Label.setText("Alo_Wala_Naan");
        Alo_Wala_Naan_Pannel.add(Alo_Wala_Naan_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        Alo_Wala_Naan_Price.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Alo_Wala_Naan_Price.setForeground(new java.awt.Color(204, 0, 0));
        Alo_Wala_Naan_Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Alo_Wala_Naan_Price.setText("Price = 30Rs.");
        Alo_Wala_Naan_Pannel.add(Alo_Wala_Naan_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Tundoor/Khameri Roti.jpg"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Tundoor/Paratha.jpg"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Tundoor/Simple Naan.jpg"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Tundoor/Simple Roti.jpg"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Tundoor/Alo wala Naan.jpg"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Images/Tundoor/Rogni Naan.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Khameere_Roti_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Alo_Wala_Naan_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Simple_Roti_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Paratha_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Simple_Naan_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22)))
                        .addGap(18, 18, 18)
                        .addComponent(Rogni_Naan_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 552, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel7))
                                            .addGap(69, 69, 69)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel12)))
                                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Paratha_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Simple_Naan_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Simple_Roti_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Rogni_Naan_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18))
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Khameere_Roti_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Alo_Wala_Naan_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ALL_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALL_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        All_Products all = new All_Products();
        all.Total_Products(this.Total_Amount);
        all.setVisible(true);
        this.dispose();
        all.Import_File();
    }//GEN-LAST:event_ALL_BUTTONActionPerformed

    private void BAR_B_Q_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAR_B_Q_BUTTON1ActionPerformed
        // TODO add your handling code here:
        Export_File();
        BAR_B_Q_Page b = new BAR_B_Q_Page();
        b.Total_BBQ(this.Total_Amount);
        b.setVisible(true);
        this.dispose();
        b.Import_File();
    }//GEN-LAST:event_BAR_B_Q_BUTTON1ActionPerformed

    private void KARAHI_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KARAHI_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        KARAHI K = new KARAHI();
        K.Total_Karahi(this.Total_Amount);
        K.setVisible(true);
        this.dispose();
        K.Import_File();
    }//GEN-LAST:event_KARAHI_BUTTONActionPerformed

    private void RICE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RICE_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        RICE rice = new RICE();
        rice.Total_Rice(this.Total_Amount);
        rice.setVisible(true);
        this.dispose();
        rice.Import_File();
    }//GEN-LAST:event_RICE_BUTTONActionPerformed

    private void VEGETABLES_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VEGETABLES_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        VEGETABLES vege = new VEGETABLES();
        vege.Total_Vegetables(this.Total_Amount);
        vege.setVisible(true);
        this.dispose();
        vege.Import_File();
    }//GEN-LAST:event_VEGETABLES_BUTTONActionPerformed

    private void BEANS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEANS_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        BEANS beans = new BEANS();
        beans.Total_Beans(this.Total_Amount);
        beans.setVisible(true);
        this.dispose();
        beans.Import_File();
    }//GEN-LAST:event_BEANS_BUTTONActionPerformed

    private void CHINES_DISHES_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHINES_DISHES_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        CHINESE_DISHES china = new CHINESE_DISHES();
        china.Total_Chinese_Dishes(this.Total_Amount);
        china.setVisible(true);
        this.dispose();
        china.Import_File();
    }//GEN-LAST:event_CHINES_DISHES_BUTTONActionPerformed

    private void FAST_FOOD_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAST_FOOD_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        FAST_FOOD fast = new FAST_FOOD();
        fast.Total_Fast_Food(this.Total_Amount);
        fast.setVisible(true);
        this.dispose();
        fast.Import_File();
    }//GEN-LAST:event_FAST_FOOD_BUTTONActionPerformed

    private void SWEETS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SWEETS_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        DESSERTS desserts = new DESSERTS();
        desserts.Total_Desserts(this.Total_Amount);
        desserts.setVisible(true);
        this.dispose();
        desserts.Import_File();
    }//GEN-LAST:event_SWEETS_BUTTONActionPerformed

    private void COLD_DRINKS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COLD_DRINKS_BUTTONActionPerformed
        // TODO add your handling code here:
        Export_File();
        BEVERAGES drinks = new BEVERAGES();
        drinks.Total_Drinks(this.Total_Amount);
        drinks.setVisible(true);
        this.dispose();
        drinks.Import_File();
    }//GEN-LAST:event_COLD_DRINKS_BUTTONActionPerformed

    private void TUNDOOR_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUNDOOR_BUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TUNDOOR_BUTTONActionPerformed

    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Delete_Row.setEnabled(false);
        Total_TextField.setText("");
        Cash_Recieved.setText("");
        Cash_Remained.setText("");

        String Total = Integer.toString(this.Total_Amount);
        Total_TextField.setText(Total);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Total_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_TextFieldActionPerformed

    private void Cash_RecievedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cash_RecievedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cash_RecievedActionPerformed

    private void Cash_RecievedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cash_RecievedKeyPressed
        // TODO add your handling code here:

        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {

            String Cash = Cash_Recieved.getText();
            int Cash_Int = Integer.parseInt(Cash);
            int Remaining_Int = Cash_Int - this.Total_Amount;
            if (Remaining_Int > 0) 
            {
                String Remaining = Integer.toString(Remaining_Int);
                Cash_Remained.setText(Remaining);
            }

        }
    }//GEN-LAST:event_Cash_RecievedKeyPressed

    private void Delete_RowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_RowActionPerformed
        // TODO add your handling code here:
        Total_TextField.setText("");
        Cash_Recieved.setText("");
        Cash_Remained.setText("");
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int i = jTable1.getSelectedRow();
        
        
        String Filepath = "E:\\Restaurant-Managememt-System-Java\\Row_Price.txt";
        File file = new File(Filepath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            bw.write(jTable1.getValueAt(i, 3).toString());
            
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Table.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        if(jTable1.getSelectedRow()>=0)
        {
            model.removeRow(jTable1.getSelectedRow());      
        }
        else
        {
            JOptionPane.showMessageDialog(null, "First Select the Row!");
        }
        
       try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);

            Object[] lines = br.lines().toArray();
            String row ="";
            for(int k =0 ; k<lines.length; k++)
            {
                row += lines[k];
            }
            int row_int = 0;
            row_int = Integer.parseInt(row);
            this.Total_Amount -= row_int;
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(KARAHI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Delete_RowActionPerformed

    private void Simple_Roti_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Simple_Roti_PannelMouseClicked
        // TODO add your handling code here:
        String name = Simple_Roti_Label.getText();

        int price = 5;
        Tundoor(name,price);
    }//GEN-LAST:event_Simple_Roti_PannelMouseClicked

    private void Paratha_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Paratha_PannelMouseClicked
        // TODO add your handling code here:
        String name = Paratha_Label.getText();

        int price = 20;
        Tundoor(name,price);
    }//GEN-LAST:event_Paratha_PannelMouseClicked

    private void Simple_Naan_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Simple_Naan_PannelMouseClicked
        // TODO add your handling code here:
        String name = Simple_Naan_Label.getText();

        int price = 10;
        Tundoor(name,price);
    }//GEN-LAST:event_Simple_Naan_PannelMouseClicked

    private void Rogni_Naan_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rogni_Naan_PannelMouseClicked
        // TODO add your handling code here:
        String name = Rogni_Naan_Label.getText();
        int price = 20;
        Tundoor(name,price);
    }//GEN-LAST:event_Rogni_Naan_PannelMouseClicked

    private void Khameere_Roti_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Khameere_Roti_PannelMouseClicked
        // TODO add your handling code here:
        String name = Khameere_Roti_Label.getText();
        int price = 7;
        Tundoor(name,price);
    }//GEN-LAST:event_Khameere_Roti_PannelMouseClicked

    private void Alo_Wala_Naan_PannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Alo_Wala_Naan_PannelMouseClicked
        // TODO add your handling code here:
        String name = Alo_Wala_Naan_Label.getText();
        int price = 30;
        Tundoor(name,price);
    }//GEN-LAST:event_Alo_Wala_Naan_PannelMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Export_File();
        Bill bill = new Bill();
        bill.Total_Bill(this.Total_Amount,Cash_Recieved.getText(),Cash_Remained.getText());
        bill.setVisible(true);
        bill.Import_File();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TUNDOOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ALL_BUTTON;
    private javax.swing.JLabel Alo_Wala_Naan_Label;
    private javax.swing.JPanel Alo_Wala_Naan_Pannel;
    private javax.swing.JLabel Alo_Wala_Naan_Price;
    private javax.swing.JButton BAR_B_Q_BUTTON1;
    private javax.swing.JButton BEANS_BUTTON;
    private javax.swing.JButton CHINES_DISHES_BUTTON;
    private javax.swing.JButton COLD_DRINKS_BUTTON;
    private javax.swing.JTextField Cash_Recieved;
    private javax.swing.JTextField Cash_Remained;
    private javax.swing.JButton Delete_Row;
    private javax.swing.JButton FAST_FOOD_BUTTON;
    private javax.swing.JButton KARAHI_BUTTON;
    private javax.swing.JLabel Khameere_Roti_Label;
    private javax.swing.JPanel Khameere_Roti_Pannel;
    private javax.swing.JLabel Khameere_Roti_Price;
    private javax.swing.JLabel Paratha_Label;
    private javax.swing.JPanel Paratha_Pannel;
    private javax.swing.JLabel Paratha_Price;
    private javax.swing.JButton RICE_BUTTON;
    private javax.swing.JLabel Rogni_Naan_Label;
    private javax.swing.JPanel Rogni_Naan_Pannel;
    private javax.swing.JLabel Rogni_Naan_Price;
    private javax.swing.JButton SWEETS_BUTTON;
    private javax.swing.JLabel Simple_Naan_Label;
    private javax.swing.JPanel Simple_Naan_Pannel;
    private javax.swing.JLabel Simple_Naan_Price;
    private javax.swing.JLabel Simple_Roti_Label;
    private javax.swing.JPanel Simple_Roti_Pannel;
    private javax.swing.JLabel Simple_Roti_Price;
    private javax.swing.JButton TUNDOOR_BUTTON;
    private javax.swing.JTextField Total_TextField;
    private javax.swing.JButton VEGETABLES_BUTTON;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
